version: "{build}"


#init:
#  - git config --global core.autocrlf input

# Build

os: Visual Studio 2019

build: off

clone_folder: c:\gopath\src\github.com\33cn\plugin

environment:
  GOPATH: c:\gopath


# set go version
before_test:
  - set PATH=C:\go116\bin;%PATH%
  - set GOROOT=C:\go116
  - go version
  - go env


test_script:
  - build.bat
#  - for /f "" %%G in ('go list github.com/33cn/plugin/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)

