// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collateralize.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 借贷信息
type Collateralize struct {
	CollateralizeId        string          `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	TotalBalance           int64           `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling            int64           `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio       float32         `protobuf:"fixed32,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio      float32         `protobuf:"fixed32,5,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	CreateAddr             string          `protobuf:"bytes,6,opt,name=createAddr,proto3" json:"createAddr,omitempty"`
	Balance                int64           `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	BorrowRecords          []*BorrowRecord `protobuf:"bytes,8,rep,name=borrowRecords,proto3" json:"borrowRecords,omitempty"`
	InvalidRecords         []*BorrowRecord `protobuf:"bytes,9,rep,name=InvalidRecords,proto3" json:"InvalidRecords,omitempty"`
	Status                 int32           `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CollType               int32           `protobuf:"varint,11,opt,name=collType,proto3" json:"collType,omitempty"`
	LatestLiquidationPrice float32         `protobuf:"fixed32,12,opt,name=latestLiquidationPrice,proto3" json:"latestLiquidationPrice,omitempty"`
	Period                 int64           `protobuf:"varint,13,opt,name=period,proto3" json:"period,omitempty"`
	LatestExpireTime       int64           `protobuf:"varint,14,opt,name=latestExpireTime,proto3" json:"latestExpireTime,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}        `json:"-"`
	XXX_unrecognized       []byte          `json:"-"`
	XXX_sizecache          int32           `json:"-"`
}

func (m *Collateralize) Reset()         { *m = Collateralize{} }
func (m *Collateralize) String() string { return proto.CompactTextString(m) }
func (*Collateralize) ProtoMessage()    {}
func (*Collateralize) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{0}
}

func (m *Collateralize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collateralize.Unmarshal(m, b)
}
func (m *Collateralize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collateralize.Marshal(b, m, deterministic)
}
func (m *Collateralize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collateralize.Merge(m, src)
}
func (m *Collateralize) XXX_Size() int {
	return xxx_messageInfo_Collateralize.Size(m)
}
func (m *Collateralize) XXX_DiscardUnknown() {
	xxx_messageInfo_Collateralize.DiscardUnknown(m)
}

var xxx_messageInfo_Collateralize proto.InternalMessageInfo

func (m *Collateralize) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *Collateralize) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *Collateralize) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *Collateralize) GetLiquidationRatio() float32 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *Collateralize) GetStabilityFeeRatio() float32 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *Collateralize) GetCreateAddr() string {
	if m != nil {
		return m.CreateAddr
	}
	return ""
}

func (m *Collateralize) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Collateralize) GetBorrowRecords() []*BorrowRecord {
	if m != nil {
		return m.BorrowRecords
	}
	return nil
}

func (m *Collateralize) GetInvalidRecords() []*BorrowRecord {
	if m != nil {
		return m.InvalidRecords
	}
	return nil
}

func (m *Collateralize) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Collateralize) GetCollType() int32 {
	if m != nil {
		return m.CollType
	}
	return 0
}

func (m *Collateralize) GetLatestLiquidationPrice() float32 {
	if m != nil {
		return m.LatestLiquidationPrice
	}
	return 0
}

func (m *Collateralize) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Collateralize) GetLatestExpireTime() int64 {
	if m != nil {
		return m.LatestExpireTime
	}
	return 0
}

// 借出记录
type BorrowRecord struct {
	AccountAddr          string   `protobuf:"bytes,1,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CollateralValue      int64    `protobuf:"varint,3,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	CollateralPrice      float32  `protobuf:"fixed32,4,opt,name=collateralPrice,proto3" json:"collateralPrice,omitempty"`
	DebtValue            int64    `protobuf:"varint,5,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	LiquidationPrice     float32  `protobuf:"fixed32,6,opt,name=liquidationPrice,proto3" json:"liquidationPrice,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	LiquidateTime        int64    `protobuf:"varint,8,opt,name=liquidateTime,proto3" json:"liquidateTime,omitempty"`
	ExpireTime           int64    `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowRecord) Reset()         { *m = BorrowRecord{} }
func (m *BorrowRecord) String() string { return proto.CompactTextString(m) }
func (*BorrowRecord) ProtoMessage()    {}
func (*BorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{1}
}

func (m *BorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowRecord.Unmarshal(m, b)
}
func (m *BorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowRecord.Marshal(b, m, deterministic)
}
func (m *BorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowRecord.Merge(m, src)
}
func (m *BorrowRecord) XXX_Size() int {
	return xxx_messageInfo_BorrowRecord.Size(m)
}
func (m *BorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowRecord proto.InternalMessageInfo

func (m *BorrowRecord) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *BorrowRecord) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BorrowRecord) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *BorrowRecord) GetCollateralPrice() float32 {
	if m != nil {
		return m.CollateralPrice
	}
	return 0
}

func (m *BorrowRecord) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *BorrowRecord) GetLiquidationPrice() float32 {
	if m != nil {
		return m.LiquidationPrice
	}
	return 0
}

func (m *BorrowRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BorrowRecord) GetLiquidateTime() int64 {
	if m != nil {
		return m.LiquidateTime
	}
	return 0
}

func (m *BorrowRecord) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

// 资产价格记录
type AssetPriceRecord struct {
	RecordTime           int64    `protobuf:"varint,1,opt,name=recordTime,proto3" json:"recordTime,omitempty"`
	BtyPrice             float32  `protobuf:"fixed32,2,opt,name=btyPrice,proto3" json:"btyPrice,omitempty"`
	BtcPrice             float32  `protobuf:"fixed32,3,opt,name=btcPrice,proto3" json:"btcPrice,omitempty"`
	EthPrice             float32  `protobuf:"fixed32,4,opt,name=ethPrice,proto3" json:"ethPrice,omitempty"`
	PreRecordTime        int64    `protobuf:"varint,5,opt,name=preRecordTime,proto3" json:"preRecordTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetPriceRecord) Reset()         { *m = AssetPriceRecord{} }
func (m *AssetPriceRecord) String() string { return proto.CompactTextString(m) }
func (*AssetPriceRecord) ProtoMessage()    {}
func (*AssetPriceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{2}
}

func (m *AssetPriceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetPriceRecord.Unmarshal(m, b)
}
func (m *AssetPriceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetPriceRecord.Marshal(b, m, deterministic)
}
func (m *AssetPriceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetPriceRecord.Merge(m, src)
}
func (m *AssetPriceRecord) XXX_Size() int {
	return xxx_messageInfo_AssetPriceRecord.Size(m)
}
func (m *AssetPriceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetPriceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AssetPriceRecord proto.InternalMessageInfo

func (m *AssetPriceRecord) GetRecordTime() int64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func (m *AssetPriceRecord) GetBtyPrice() float32 {
	if m != nil {
		return m.BtyPrice
	}
	return 0
}

func (m *AssetPriceRecord) GetBtcPrice() float32 {
	if m != nil {
		return m.BtcPrice
	}
	return 0
}

func (m *AssetPriceRecord) GetEthPrice() float32 {
	if m != nil {
		return m.EthPrice
	}
	return 0
}

func (m *AssetPriceRecord) GetPreRecordTime() int64 {
	if m != nil {
		return m.PreRecordTime
	}
	return 0
}

// action
type CollateralizeAction struct {
	// Types that are valid to be assigned to Value:
	//	*CollateralizeAction_Create
	//	*CollateralizeAction_Borrow
	//	*CollateralizeAction_Repay
	//	*CollateralizeAction_Append
	//	*CollateralizeAction_Feed
	//	*CollateralizeAction_Close
	//	*CollateralizeAction_Manage
	Value                isCollateralizeAction_Value `protobuf_oneof:"value"`
	Ty                   int32                       `protobuf:"varint,10,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CollateralizeAction) Reset()         { *m = CollateralizeAction{} }
func (m *CollateralizeAction) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAction) ProtoMessage()    {}
func (*CollateralizeAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{3}
}

func (m *CollateralizeAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAction.Unmarshal(m, b)
}
func (m *CollateralizeAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAction.Marshal(b, m, deterministic)
}
func (m *CollateralizeAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAction.Merge(m, src)
}
func (m *CollateralizeAction) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAction.Size(m)
}
func (m *CollateralizeAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAction.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAction proto.InternalMessageInfo

type isCollateralizeAction_Value interface {
	isCollateralizeAction_Value()
}

type CollateralizeAction_Create struct {
	Create *CollateralizeCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CollateralizeAction_Borrow struct {
	Borrow *CollateralizeBorrow `protobuf:"bytes,2,opt,name=borrow,proto3,oneof"`
}

type CollateralizeAction_Repay struct {
	Repay *CollateralizeRepay `protobuf:"bytes,3,opt,name=repay,proto3,oneof"`
}

type CollateralizeAction_Append struct {
	Append *CollateralizeAppend `protobuf:"bytes,4,opt,name=append,proto3,oneof"`
}

type CollateralizeAction_Feed struct {
	Feed *CollateralizeFeed `protobuf:"bytes,5,opt,name=feed,proto3,oneof"`
}

type CollateralizeAction_Close struct {
	Close *CollateralizeClose `protobuf:"bytes,6,opt,name=close,proto3,oneof"`
}

type CollateralizeAction_Manage struct {
	Manage *CollateralizeManage `protobuf:"bytes,7,opt,name=manage,proto3,oneof"`
}

func (*CollateralizeAction_Create) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Borrow) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Repay) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Append) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Feed) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Close) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Manage) isCollateralizeAction_Value() {}

func (m *CollateralizeAction) GetValue() isCollateralizeAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CollateralizeAction) GetCreate() *CollateralizeCreate {
	if x, ok := m.GetValue().(*CollateralizeAction_Create); ok {
		return x.Create
	}
	return nil
}

func (m *CollateralizeAction) GetBorrow() *CollateralizeBorrow {
	if x, ok := m.GetValue().(*CollateralizeAction_Borrow); ok {
		return x.Borrow
	}
	return nil
}

func (m *CollateralizeAction) GetRepay() *CollateralizeRepay {
	if x, ok := m.GetValue().(*CollateralizeAction_Repay); ok {
		return x.Repay
	}
	return nil
}

func (m *CollateralizeAction) GetAppend() *CollateralizeAppend {
	if x, ok := m.GetValue().(*CollateralizeAction_Append); ok {
		return x.Append
	}
	return nil
}

func (m *CollateralizeAction) GetFeed() *CollateralizeFeed {
	if x, ok := m.GetValue().(*CollateralizeAction_Feed); ok {
		return x.Feed
	}
	return nil
}

func (m *CollateralizeAction) GetClose() *CollateralizeClose {
	if x, ok := m.GetValue().(*CollateralizeAction_Close); ok {
		return x.Close
	}
	return nil
}

func (m *CollateralizeAction) GetManage() *CollateralizeManage {
	if x, ok := m.GetValue().(*CollateralizeAction_Manage); ok {
		return x.Manage
	}
	return nil
}

func (m *CollateralizeAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CollateralizeAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CollateralizeAction_Create)(nil),
		(*CollateralizeAction_Borrow)(nil),
		(*CollateralizeAction_Repay)(nil),
		(*CollateralizeAction_Append)(nil),
		(*CollateralizeAction_Feed)(nil),
		(*CollateralizeAction_Close)(nil),
		(*CollateralizeAction_Manage)(nil),
	}
}

type CollateralizeManage struct {
	Cfg                  *CollateralizeConfig `protobuf:"bytes,1,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Addr                 *CollateralizeAddr   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CollateralizeManage) Reset()         { *m = CollateralizeManage{} }
func (m *CollateralizeManage) String() string { return proto.CompactTextString(m) }
func (*CollateralizeManage) ProtoMessage()    {}
func (*CollateralizeManage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{4}
}

func (m *CollateralizeManage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeManage.Unmarshal(m, b)
}
func (m *CollateralizeManage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeManage.Marshal(b, m, deterministic)
}
func (m *CollateralizeManage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeManage.Merge(m, src)
}
func (m *CollateralizeManage) XXX_Size() int {
	return xxx_messageInfo_CollateralizeManage.Size(m)
}
func (m *CollateralizeManage) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeManage.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeManage proto.InternalMessageInfo

func (m *CollateralizeManage) GetCfg() *CollateralizeConfig {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *CollateralizeManage) GetAddr() *CollateralizeAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

type CollateralizeConfig struct {
	DebtCeiling          int64    `protobuf:"varint,1,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     float32  `protobuf:"fixed32,2,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    float32  `protobuf:"fixed32,3,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	Period               int64    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeConfig) Reset()         { *m = CollateralizeConfig{} }
func (m *CollateralizeConfig) String() string { return proto.CompactTextString(m) }
func (*CollateralizeConfig) ProtoMessage()    {}
func (*CollateralizeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{5}
}

func (m *CollateralizeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeConfig.Unmarshal(m, b)
}
func (m *CollateralizeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeConfig.Marshal(b, m, deterministic)
}
func (m *CollateralizeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeConfig.Merge(m, src)
}
func (m *CollateralizeConfig) XXX_Size() int {
	return xxx_messageInfo_CollateralizeConfig.Size(m)
}
func (m *CollateralizeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeConfig proto.InternalMessageInfo

func (m *CollateralizeConfig) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *CollateralizeConfig) GetLiquidationRatio() float32 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *CollateralizeConfig) GetStabilityFeeRatio() float32 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *CollateralizeConfig) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type CollateralizeAddr struct {
	SuperAddrs           []string `protobuf:"bytes,1,rep,name=superAddrs,proto3" json:"superAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeAddr) Reset()         { *m = CollateralizeAddr{} }
func (m *CollateralizeAddr) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAddr) ProtoMessage()    {}
func (*CollateralizeAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{6}
}

func (m *CollateralizeAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAddr.Unmarshal(m, b)
}
func (m *CollateralizeAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAddr.Marshal(b, m, deterministic)
}
func (m *CollateralizeAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAddr.Merge(m, src)
}
func (m *CollateralizeAddr) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAddr.Size(m)
}
func (m *CollateralizeAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAddr.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAddr proto.InternalMessageInfo

func (m *CollateralizeAddr) GetSuperAddrs() []string {
	if m != nil {
		return m.SuperAddrs
	}
	return nil
}

// 创建借贷
type CollateralizeCreate struct {
	TotalBalance         int64    `protobuf:"varint,1,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeCreate) Reset()         { *m = CollateralizeCreate{} }
func (m *CollateralizeCreate) String() string { return proto.CompactTextString(m) }
func (*CollateralizeCreate) ProtoMessage()    {}
func (*CollateralizeCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{7}
}

func (m *CollateralizeCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeCreate.Unmarshal(m, b)
}
func (m *CollateralizeCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeCreate.Marshal(b, m, deterministic)
}
func (m *CollateralizeCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeCreate.Merge(m, src)
}
func (m *CollateralizeCreate) XXX_Size() int {
	return xxx_messageInfo_CollateralizeCreate.Size(m)
}
func (m *CollateralizeCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeCreate.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeCreate proto.InternalMessageInfo

func (m *CollateralizeCreate) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

// 质押借出
type CollateralizeBorrow struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeBorrow) Reset()         { *m = CollateralizeBorrow{} }
func (m *CollateralizeBorrow) String() string { return proto.CompactTextString(m) }
func (*CollateralizeBorrow) ProtoMessage()    {}
func (*CollateralizeBorrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{8}
}

func (m *CollateralizeBorrow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeBorrow.Unmarshal(m, b)
}
func (m *CollateralizeBorrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeBorrow.Marshal(b, m, deterministic)
}
func (m *CollateralizeBorrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeBorrow.Merge(m, src)
}
func (m *CollateralizeBorrow) XXX_Size() int {
	return xxx_messageInfo_CollateralizeBorrow.Size(m)
}
func (m *CollateralizeBorrow) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeBorrow.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeBorrow proto.InternalMessageInfo

func (m *CollateralizeBorrow) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeBorrow) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 质押清算
type CollateralizeRepay struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeRepay) Reset()         { *m = CollateralizeRepay{} }
func (m *CollateralizeRepay) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRepay) ProtoMessage()    {}
func (*CollateralizeRepay) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{9}
}

func (m *CollateralizeRepay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRepay.Unmarshal(m, b)
}
func (m *CollateralizeRepay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRepay.Marshal(b, m, deterministic)
}
func (m *CollateralizeRepay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRepay.Merge(m, src)
}
func (m *CollateralizeRepay) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRepay.Size(m)
}
func (m *CollateralizeRepay) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRepay.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRepay proto.InternalMessageInfo

func (m *CollateralizeRepay) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeRepay) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 追加抵押物
type CollateralizeAppend struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	CollateralValue      int64    `protobuf:"varint,2,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeAppend) Reset()         { *m = CollateralizeAppend{} }
func (m *CollateralizeAppend) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAppend) ProtoMessage()    {}
func (*CollateralizeAppend) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{10}
}

func (m *CollateralizeAppend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAppend.Unmarshal(m, b)
}
func (m *CollateralizeAppend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAppend.Marshal(b, m, deterministic)
}
func (m *CollateralizeAppend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAppend.Merge(m, src)
}
func (m *CollateralizeAppend) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAppend.Size(m)
}
func (m *CollateralizeAppend) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAppend.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAppend proto.InternalMessageInfo

func (m *CollateralizeAppend) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeAppend) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

// 喂价
type CollateralizeFeed struct {
	CollType             int32     `protobuf:"varint,1,opt,name=collType,proto3" json:"collType,omitempty"`
	Price                []float32 `protobuf:"fixed32,2,rep,packed,name=price,proto3" json:"price,omitempty"`
	Volume               []int64   `protobuf:"varint,3,rep,packed,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CollateralizeFeed) Reset()         { *m = CollateralizeFeed{} }
func (m *CollateralizeFeed) String() string { return proto.CompactTextString(m) }
func (*CollateralizeFeed) ProtoMessage()    {}
func (*CollateralizeFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{11}
}

func (m *CollateralizeFeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeFeed.Unmarshal(m, b)
}
func (m *CollateralizeFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeFeed.Marshal(b, m, deterministic)
}
func (m *CollateralizeFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeFeed.Merge(m, src)
}
func (m *CollateralizeFeed) XXX_Size() int {
	return xxx_messageInfo_CollateralizeFeed.Size(m)
}
func (m *CollateralizeFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeFeed.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeFeed proto.InternalMessageInfo

func (m *CollateralizeFeed) GetCollType() int32 {
	if m != nil {
		return m.CollType
	}
	return 0
}

func (m *CollateralizeFeed) GetPrice() []float32 {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *CollateralizeFeed) GetVolume() []int64 {
	if m != nil {
		return m.Volume
	}
	return nil
}

// 借贷关闭
type CollateralizeClose struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeClose) Reset()         { *m = CollateralizeClose{} }
func (m *CollateralizeClose) String() string { return proto.CompactTextString(m) }
func (*CollateralizeClose) ProtoMessage()    {}
func (*CollateralizeClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{12}
}

func (m *CollateralizeClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeClose.Unmarshal(m, b)
}
func (m *CollateralizeClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeClose.Marshal(b, m, deterministic)
}
func (m *CollateralizeClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeClose.Merge(m, src)
}
func (m *CollateralizeClose) XXX_Size() int {
	return xxx_messageInfo_CollateralizeClose.Size(m)
}
func (m *CollateralizeClose) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeClose.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeClose proto.InternalMessageInfo

func (m *CollateralizeClose) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

// exec_local 借贷信息
type ReceiptCollateralize struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	CreateAddr           string   `protobuf:"bytes,2,opt,name=createAddr,proto3" json:"createAddr,omitempty"`
	AccountAddr          string   `protobuf:"bytes,3,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	PreStatus            int32    `protobuf:"varint,5,opt,name=preStatus,proto3" json:"preStatus,omitempty"`
	Index                int64    `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	RecordStatus         int32    `protobuf:"varint,7,opt,name=recordStatus,proto3" json:"recordStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptCollateralize) Reset()         { *m = ReceiptCollateralize{} }
func (m *ReceiptCollateralize) String() string { return proto.CompactTextString(m) }
func (*ReceiptCollateralize) ProtoMessage()    {}
func (*ReceiptCollateralize) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{13}
}

func (m *ReceiptCollateralize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptCollateralize.Unmarshal(m, b)
}
func (m *ReceiptCollateralize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptCollateralize.Marshal(b, m, deterministic)
}
func (m *ReceiptCollateralize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptCollateralize.Merge(m, src)
}
func (m *ReceiptCollateralize) XXX_Size() int {
	return xxx_messageInfo_ReceiptCollateralize.Size(m)
}
func (m *ReceiptCollateralize) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptCollateralize.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptCollateralize proto.InternalMessageInfo

func (m *ReceiptCollateralize) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReceiptCollateralize) GetCreateAddr() string {
	if m != nil {
		return m.CreateAddr
	}
	return ""
}

func (m *ReceiptCollateralize) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *ReceiptCollateralize) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReceiptCollateralize) GetPreStatus() int32 {
	if m != nil {
		return m.PreStatus
	}
	return 0
}

func (m *ReceiptCollateralize) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReceiptCollateralize) GetRecordStatus() int32 {
	if m != nil {
		return m.RecordStatus
	}
	return 0
}

// exec_local 借贷记录信息
type CollateralizeRecord struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeRecord) Reset()         { *m = CollateralizeRecord{} }
func (m *CollateralizeRecord) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRecord) ProtoMessage()    {}
func (*CollateralizeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{14}
}

func (m *CollateralizeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRecord.Unmarshal(m, b)
}
func (m *CollateralizeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRecord.Marshal(b, m, deterministic)
}
func (m *CollateralizeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRecord.Merge(m, src)
}
func (m *CollateralizeRecord) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRecord.Size(m)
}
func (m *CollateralizeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRecord proto.InternalMessageInfo

func (m *CollateralizeRecord) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *CollateralizeRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// exec_local 借贷记录信息列表
type CollateralizeRecords struct {
	Records              []*CollateralizeRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CollateralizeRecords) Reset()         { *m = CollateralizeRecords{} }
func (m *CollateralizeRecords) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRecords) ProtoMessage()    {}
func (*CollateralizeRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{15}
}

func (m *CollateralizeRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRecords.Unmarshal(m, b)
}
func (m *CollateralizeRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRecords.Marshal(b, m, deterministic)
}
func (m *CollateralizeRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRecords.Merge(m, src)
}
func (m *CollateralizeRecords) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRecords.Size(m)
}
func (m *CollateralizeRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRecords.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRecords proto.InternalMessageInfo

func (m *CollateralizeRecords) GetRecords() []*CollateralizeRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// 根据ID查询一期借贷信息
type ReqCollateralizeInfo struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeInfo) Reset()         { *m = ReqCollateralizeInfo{} }
func (m *ReqCollateralizeInfo) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeInfo) ProtoMessage()    {}
func (*ReqCollateralizeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{16}
}

func (m *ReqCollateralizeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeInfo.Unmarshal(m, b)
}
func (m *ReqCollateralizeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeInfo.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeInfo.Merge(m, src)
}
func (m *ReqCollateralizeInfo) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeInfo.Size(m)
}
func (m *ReqCollateralizeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeInfo proto.InternalMessageInfo

func (m *ReqCollateralizeInfo) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

// 返回一期借贷信息
type RepCollateralizeCurrentInfo struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalBalance         int64    `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling          int64    `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     float32  `protobuf:"fixed32,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    float32  `protobuf:"fixed32,5,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	LiquidationPenalty   int64    `protobuf:"varint,6,opt,name=liquidationPenalty,proto3" json:"liquidationPenalty,omitempty"`
	CreateAddr           string   `protobuf:"bytes,7,opt,name=createAddr,proto3" json:"createAddr,omitempty"`
	Balance              int64    `protobuf:"varint,8,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeCurrentInfo) Reset()         { *m = RepCollateralizeCurrentInfo{} }
func (m *RepCollateralizeCurrentInfo) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeCurrentInfo) ProtoMessage()    {}
func (*RepCollateralizeCurrentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{17}
}

func (m *RepCollateralizeCurrentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Unmarshal(m, b)
}
func (m *RepCollateralizeCurrentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeCurrentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeCurrentInfo.Merge(m, src)
}
func (m *RepCollateralizeCurrentInfo) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Size(m)
}
func (m *RepCollateralizeCurrentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeCurrentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeCurrentInfo proto.InternalMessageInfo

func (m *RepCollateralizeCurrentInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetLiquidationRatio() float32 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetStabilityFeeRatio() float32 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetLiquidationPenalty() int64 {
	if m != nil {
		return m.LiquidationPenalty
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetCreateAddr() string {
	if m != nil {
		return m.CreateAddr
	}
	return ""
}

func (m *RepCollateralizeCurrentInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 根据ID列表查询多期借贷信息
type ReqCollateralizeInfos struct {
	CollateralizeIds     []string `protobuf:"bytes,1,rep,name=collateralizeIds,proto3" json:"collateralizeIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeInfos) Reset()         { *m = ReqCollateralizeInfos{} }
func (m *ReqCollateralizeInfos) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeInfos) ProtoMessage()    {}
func (*ReqCollateralizeInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{18}
}

func (m *ReqCollateralizeInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeInfos.Unmarshal(m, b)
}
func (m *ReqCollateralizeInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeInfos.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeInfos.Merge(m, src)
}
func (m *ReqCollateralizeInfos) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeInfos.Size(m)
}
func (m *ReqCollateralizeInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeInfos.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeInfos proto.InternalMessageInfo

func (m *ReqCollateralizeInfos) GetCollateralizeIds() []string {
	if m != nil {
		return m.CollateralizeIds
	}
	return nil
}

// 返回多期借贷信息
type RepCollateralizeCurrentInfos struct {
	Infos                []*RepCollateralizeCurrentInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RepCollateralizeCurrentInfos) Reset()         { *m = RepCollateralizeCurrentInfos{} }
func (m *RepCollateralizeCurrentInfos) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeCurrentInfos) ProtoMessage()    {}
func (*RepCollateralizeCurrentInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{19}
}

func (m *RepCollateralizeCurrentInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Unmarshal(m, b)
}
func (m *RepCollateralizeCurrentInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeCurrentInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeCurrentInfos.Merge(m, src)
}
func (m *RepCollateralizeCurrentInfos) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Size(m)
}
func (m *RepCollateralizeCurrentInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeCurrentInfos.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeCurrentInfos proto.InternalMessageInfo

func (m *RepCollateralizeCurrentInfos) GetInfos() []*RepCollateralizeCurrentInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

// 根据借贷状态查询
type ReqCollateralizeByStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeByStatus) Reset()         { *m = ReqCollateralizeByStatus{} }
func (m *ReqCollateralizeByStatus) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeByStatus) ProtoMessage()    {}
func (*ReqCollateralizeByStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{20}
}

func (m *ReqCollateralizeByStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeByStatus.Unmarshal(m, b)
}
func (m *ReqCollateralizeByStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeByStatus.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeByStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeByStatus.Merge(m, src)
}
func (m *ReqCollateralizeByStatus) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeByStatus.Size(m)
}
func (m *ReqCollateralizeByStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeByStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeByStatus proto.InternalMessageInfo

func (m *ReqCollateralizeByStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 根据用户地址查询
type ReqCollateralizeByAddr struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeByAddr) Reset()         { *m = ReqCollateralizeByAddr{} }
func (m *ReqCollateralizeByAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeByAddr) ProtoMessage()    {}
func (*ReqCollateralizeByAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{21}
}

func (m *ReqCollateralizeByAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeByAddr.Unmarshal(m, b)
}
func (m *ReqCollateralizeByAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeByAddr.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeByAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeByAddr.Merge(m, src)
}
func (m *ReqCollateralizeByAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeByAddr.Size(m)
}
func (m *ReqCollateralizeByAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeByAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeByAddr proto.InternalMessageInfo

func (m *ReqCollateralizeByAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 返回借贷ID列表
type RepCollateralizeIDs struct {
	IDs                  []string `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeIDs) Reset()         { *m = RepCollateralizeIDs{} }
func (m *RepCollateralizeIDs) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeIDs) ProtoMessage()    {}
func (*RepCollateralizeIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{22}
}

func (m *RepCollateralizeIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeIDs.Unmarshal(m, b)
}
func (m *RepCollateralizeIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeIDs.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeIDs.Merge(m, src)
}
func (m *RepCollateralizeIDs) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeIDs.Size(m)
}
func (m *RepCollateralizeIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeIDs.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeIDs proto.InternalMessageInfo

func (m *RepCollateralizeIDs) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

// 根据地址和借贷ID混合查询具体借贷记录
type ReqCollateralizeBorrowInfoByAddr struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeBorrowInfoByAddr) Reset()         { *m = ReqCollateralizeBorrowInfoByAddr{} }
func (m *ReqCollateralizeBorrowInfoByAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeBorrowInfoByAddr) ProtoMessage()    {}
func (*ReqCollateralizeBorrowInfoByAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{23}
}

func (m *ReqCollateralizeBorrowInfoByAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr.Unmarshal(m, b)
}
func (m *ReqCollateralizeBorrowInfoByAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeBorrowInfoByAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr.Merge(m, src)
}
func (m *ReqCollateralizeBorrowInfoByAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr.Size(m)
}
func (m *ReqCollateralizeBorrowInfoByAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeBorrowInfoByAddr proto.InternalMessageInfo

func (m *ReqCollateralizeBorrowInfoByAddr) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReqCollateralizeBorrowInfoByAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 根据状态和借贷ID混合查询具体借贷记录
type ReqCollateralizeBorrowInfoByStatus struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeBorrowInfoByStatus) Reset()         { *m = ReqCollateralizeBorrowInfoByStatus{} }
func (m *ReqCollateralizeBorrowInfoByStatus) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeBorrowInfoByStatus) ProtoMessage()    {}
func (*ReqCollateralizeBorrowInfoByStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{24}
}

func (m *ReqCollateralizeBorrowInfoByStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus.Unmarshal(m, b)
}
func (m *ReqCollateralizeBorrowInfoByStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeBorrowInfoByStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus.Merge(m, src)
}
func (m *ReqCollateralizeBorrowInfoByStatus) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus.Size(m)
}
func (m *ReqCollateralizeBorrowInfoByStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeBorrowInfoByStatus proto.InternalMessageInfo

func (m *ReqCollateralizeBorrowInfoByStatus) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReqCollateralizeBorrowInfoByStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 返回借贷记录
type RepCollateralizeBorrowInfos struct {
	Record               []*BorrowRecord `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RepCollateralizeBorrowInfos) Reset()         { *m = RepCollateralizeBorrowInfos{} }
func (m *RepCollateralizeBorrowInfos) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeBorrowInfos) ProtoMessage()    {}
func (*RepCollateralizeBorrowInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{25}
}

func (m *RepCollateralizeBorrowInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeBorrowInfos.Unmarshal(m, b)
}
func (m *RepCollateralizeBorrowInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeBorrowInfos.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeBorrowInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeBorrowInfos.Merge(m, src)
}
func (m *RepCollateralizeBorrowInfos) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeBorrowInfos.Size(m)
}
func (m *RepCollateralizeBorrowInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeBorrowInfos.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeBorrowInfos proto.InternalMessageInfo

func (m *RepCollateralizeBorrowInfos) GetRecord() []*BorrowRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterType((*Collateralize)(nil), "types.Collateralize")
	proto.RegisterType((*BorrowRecord)(nil), "types.BorrowRecord")
	proto.RegisterType((*AssetPriceRecord)(nil), "types.AssetPriceRecord")
	proto.RegisterType((*CollateralizeAction)(nil), "types.CollateralizeAction")
	proto.RegisterType((*CollateralizeManage)(nil), "types.CollateralizeManage")
	proto.RegisterType((*CollateralizeConfig)(nil), "types.CollateralizeConfig")
	proto.RegisterType((*CollateralizeAddr)(nil), "types.CollateralizeAddr")
	proto.RegisterType((*CollateralizeCreate)(nil), "types.CollateralizeCreate")
	proto.RegisterType((*CollateralizeBorrow)(nil), "types.CollateralizeBorrow")
	proto.RegisterType((*CollateralizeRepay)(nil), "types.CollateralizeRepay")
	proto.RegisterType((*CollateralizeAppend)(nil), "types.CollateralizeAppend")
	proto.RegisterType((*CollateralizeFeed)(nil), "types.CollateralizeFeed")
	proto.RegisterType((*CollateralizeClose)(nil), "types.CollateralizeClose")
	proto.RegisterType((*ReceiptCollateralize)(nil), "types.ReceiptCollateralize")
	proto.RegisterType((*CollateralizeRecord)(nil), "types.CollateralizeRecord")
	proto.RegisterType((*CollateralizeRecords)(nil), "types.CollateralizeRecords")
	proto.RegisterType((*ReqCollateralizeInfo)(nil), "types.ReqCollateralizeInfo")
	proto.RegisterType((*RepCollateralizeCurrentInfo)(nil), "types.RepCollateralizeCurrentInfo")
	proto.RegisterType((*ReqCollateralizeInfos)(nil), "types.ReqCollateralizeInfos")
	proto.RegisterType((*RepCollateralizeCurrentInfos)(nil), "types.RepCollateralizeCurrentInfos")
	proto.RegisterType((*ReqCollateralizeByStatus)(nil), "types.ReqCollateralizeByStatus")
	proto.RegisterType((*ReqCollateralizeByAddr)(nil), "types.ReqCollateralizeByAddr")
	proto.RegisterType((*RepCollateralizeIDs)(nil), "types.RepCollateralizeIDs")
	proto.RegisterType((*ReqCollateralizeBorrowInfoByAddr)(nil), "types.ReqCollateralizeBorrowInfoByAddr")
	proto.RegisterType((*ReqCollateralizeBorrowInfoByStatus)(nil), "types.ReqCollateralizeBorrowInfoByStatus")
	proto.RegisterType((*RepCollateralizeBorrowInfos)(nil), "types.RepCollateralizeBorrowInfos")
}

func init() { proto.RegisterFile("collateralize.proto", fileDescriptor_a988fb4a61381972) }

var fileDescriptor_a988fb4a61381972 = []byte{
	// 1125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0x3f, 0xdb, 0xf9, 0xd3, 0x4c, 0xae, 0xa5, 0xb7, 0x2d, 0x95, 0x29, 0xd5, 0x29, 0x5a, 0x21,
	0x11, 0x41, 0x55, 0x89, 0xde, 0x09, 0x71, 0x42, 0x42, 0xb4, 0x39, 0x4e, 0x17, 0x74, 0x48, 0xc8,
	0x57, 0x10, 0x5f, 0x90, 0x70, 0xec, 0x4d, 0xb1, 0xe4, 0xda, 0xae, 0xbd, 0x29, 0x17, 0x9e, 0x85,
	0x17, 0x40, 0xe2, 0x0d, 0xf8, 0xc0, 0x77, 0x1e, 0x87, 0x27, 0x40, 0x33, 0xbb, 0x89, 0xed, 0x75,
	0x12, 0xa5, 0xdc, 0x17, 0xbe, 0x54, 0xdd, 0xd9, 0xdf, 0x78, 0xfe, 0xfd, 0x66, 0x66, 0x03, 0x07,
	0x41, 0x1a, 0xc7, 0xbe, 0x14, 0xb9, 0x1f, 0x47, 0xbf, 0x8a, 0xb3, 0x2c, 0x4f, 0x65, 0xca, 0xda,
	0x72, 0x9e, 0x89, 0x82, 0xff, 0xd9, 0x82, 0xdd, 0x51, 0xf5, 0x9a, 0x0d, 0xe1, 0x9d, 0x1a, 0x7e,
	0x1c, 0xba, 0xd6, 0xc0, 0x1a, 0xf6, 0x3c, 0x53, 0xcc, 0x38, 0x3c, 0x94, 0xa9, 0xf4, 0xe3, 0x4b,
	0x3f, 0xf6, 0x93, 0x40, 0xb8, 0xf6, 0xc0, 0x1a, 0x3a, 0x5e, 0x4d, 0xc6, 0x06, 0xd0, 0x0f, 0xc5,
	0x44, 0x8e, 0x44, 0x14, 0x47, 0xc9, 0xb5, 0xeb, 0x10, 0xa4, 0x2a, 0x62, 0x1f, 0xc1, 0x7e, 0x1c,
	0xdd, 0xce, 0xa2, 0xd0, 0x97, 0x51, 0x9a, 0x78, 0xf8, 0xd7, 0x6d, 0x0d, 0xac, 0xa1, 0xed, 0x35,
	0xe4, 0xec, 0x14, 0x1e, 0x15, 0xd2, 0x9f, 0x44, 0x71, 0x24, 0xe7, 0x2f, 0x84, 0x50, 0xe0, 0x36,
	0x81, 0x9b, 0x17, 0xec, 0x31, 0x40, 0x90, 0x0b, 0x5f, 0x8a, 0x8b, 0x30, 0xcc, 0xdd, 0x0e, 0x05,
	0x51, 0x91, 0x30, 0x17, 0xba, 0x13, 0xed, 0x7a, 0x97, 0xfc, 0x5a, 0x1c, 0xd9, 0x33, 0xd8, 0x9d,
	0xa4, 0x79, 0x9e, 0xfe, 0xe2, 0x89, 0x20, 0xcd, 0xc3, 0xc2, 0xdd, 0x19, 0x38, 0xc3, 0xfe, 0xf9,
	0xc1, 0x19, 0x25, 0xed, 0xec, 0xb2, 0x72, 0xe7, 0xd5, 0x91, 0xec, 0x73, 0xd8, 0x1b, 0x27, 0x77,
	0x7e, 0x1c, 0x85, 0x0b, 0xdd, 0xde, 0x7a, 0x5d, 0x03, 0xca, 0x8e, 0xa0, 0x53, 0x48, 0x5f, 0xce,
	0x0a, 0x17, 0x06, 0xd6, 0xb0, 0xed, 0xe9, 0x13, 0x3b, 0x86, 0x1d, 0x4c, 0xfe, 0xd5, 0x3c, 0x13,
	0x6e, 0x9f, 0x6e, 0x96, 0x67, 0xf6, 0x29, 0x1c, 0x61, 0x55, 0x0a, 0xf9, 0xaa, 0xcc, 0xd6, 0xb7,
	0x79, 0x14, 0x08, 0xf7, 0x21, 0x25, 0x66, 0xcd, 0x2d, 0xda, 0xca, 0x44, 0x1e, 0xa5, 0xa1, 0xbb,
	0x4b, 0xc1, 0xeb, 0x13, 0xd5, 0x83, 0x34, 0xbe, 0x7a, 0x93, 0x45, 0xb9, 0xb8, 0x8a, 0x6e, 0x84,
	0xbb, 0x47, 0x88, 0x86, 0x9c, 0xff, 0x6d, 0xc3, 0xc3, 0x6a, 0x40, 0x58, 0x6e, 0x3f, 0x08, 0xd2,
	0x59, 0x22, 0x29, 0xe7, 0x8a, 0x38, 0x55, 0x11, 0x3b, 0x81, 0x5e, 0x21, 0xfd, 0x5c, 0xd2, 0x77,
	0x15, 0x63, 0x4a, 0x41, 0x9d, 0x7c, 0xdf, 0xfb, 0xf1, 0x4c, 0x68, 0xca, 0x98, 0xe2, 0x3a, 0x52,
	0xc5, 0xab, 0x58, 0x63, 0x8a, 0xd1, 0x22, 0xf2, 0x4d, 0x7d, 0xad, 0xad, 0x2c, 0x2e, 0x05, 0x06,
	0xfd, 0xd4, 0x87, 0x3a, 0x0d, 0xfa, 0x2d, 0x53, 0xa6, 0xcb, 0xd3, 0xad, 0x95, 0xe7, 0x03, 0xd8,
	0x5d, 0x60, 0x55, 0xbe, 0x76, 0xc8, 0x4a, 0x5d, 0x88, 0x74, 0x14, 0x65, 0x4a, 0x7b, 0x04, 0xa9,
	0x48, 0xf8, 0x1f, 0x16, 0xec, 0x5f, 0x14, 0x85, 0x90, 0x64, 0x4c, 0x27, 0xf4, 0x31, 0x40, 0x4e,
	0xff, 0x91, 0x92, 0xa5, 0x94, 0x4a, 0x09, 0x32, 0x63, 0x22, 0xe7, 0xca, 0x6d, 0x9b, 0xdc, 0x5e,
	0x9e, 0xd5, 0x5d, 0xa0, 0xee, 0x9c, 0xc5, 0x5d, 0xb0, 0xbc, 0x13, 0xf2, 0xe7, 0x6a, 0xde, 0x96,
	0x67, 0x0c, 0x27, 0xcb, 0xb5, 0x03, 0x64, 0x56, 0x25, 0xad, 0x2e, 0xe4, 0xbf, 0x39, 0x70, 0x50,
	0x9b, 0x1c, 0x17, 0x01, 0x66, 0x8a, 0x3d, 0x85, 0x8e, 0xea, 0x31, 0xf2, 0xb6, 0x7f, 0x7e, 0xac,
	0x89, 0x5f, 0xc3, 0x8e, 0x08, 0xf1, 0xf2, 0x81, 0xa7, 0xb1, 0xa8, 0xa5, 0xfa, 0x88, 0xa2, 0x58,
	0xa3, 0xa5, 0xa8, 0x86, 0x5a, 0x0a, 0xcb, 0x3e, 0x81, 0x76, 0x2e, 0x32, 0x7f, 0x4e, 0xe1, 0xf5,
	0xcf, 0xdf, 0x5b, 0xa5, 0xe4, 0x21, 0xe0, 0xe5, 0x03, 0x4f, 0x21, 0xd1, 0x90, 0x9f, 0x65, 0x22,
	0x09, 0x29, 0xec, 0x35, 0x86, 0x2e, 0x08, 0x81, 0x86, 0x14, 0x96, 0x9d, 0x41, 0x6b, 0x2a, 0x44,
	0x48, 0x99, 0xe8, 0x9f, 0xbb, 0xab, 0x74, 0x5e, 0x08, 0x81, 0x1a, 0x84, 0x43, 0xc7, 0x82, 0x38,
	0x2d, 0x14, 0x95, 0xd6, 0x38, 0x36, 0x42, 0x00, 0x3a, 0x46, 0x48, 0x74, 0xec, 0xc6, 0x4f, 0xfc,
	0x6b, 0x35, 0x8c, 0xd6, 0x38, 0xf6, 0x0d, 0x21, 0xd0, 0x31, 0x85, 0x65, 0x7b, 0x60, 0xcb, 0xb9,
	0x9e, 0x16, 0xb6, 0x9c, 0x5f, 0x76, 0xa1, 0x7d, 0x87, 0xbc, 0xe6, 0xb7, 0x46, 0x75, 0x94, 0x26,
	0x3b, 0x05, 0x27, 0x98, 0x5e, 0x6f, 0x2c, 0x4d, 0x9a, 0x4c, 0xa3, 0x6b, 0x0f, 0x61, 0xec, 0x14,
	0x5a, 0x3e, 0xf6, 0xb1, 0xbd, 0x3e, 0x6c, 0x6c, 0x6a, 0x8f, 0x50, 0xfc, 0x77, 0xcb, 0xb0, 0xa9,
	0x3e, 0x65, 0xee, 0x00, 0x6b, 0xbb, 0x1d, 0x60, 0xdf, 0x67, 0x07, 0x38, 0xeb, 0x76, 0x40, 0x39,
	0xe5, 0x5a, 0xd5, 0x29, 0xc7, 0x9f, 0xc0, 0xa3, 0x46, 0x18, 0xd8, 0x6c, 0xc5, 0x2c, 0x13, 0x39,
	0x1e, 0x0a, 0xd7, 0x1a, 0x38, 0xb8, 0x30, 0x4a, 0x09, 0x7f, 0x66, 0xc6, 0xa7, 0xb8, 0x6b, 0xee,
	0x41, 0xab, 0xb9, 0x07, 0xf9, 0x77, 0x86, 0xaa, 0xa2, 0xf2, 0x3d, 0x96, 0xed, 0xa1, 0x2e, 0xac,
	0x9e, 0x99, 0xba, 0xca, 0x57, 0xc0, 0x9a, 0x64, 0x7f, 0xeb, 0xaf, 0x46, 0x66, 0x67, 0xab, 0x26,
	0xd8, 0xfe, 0xb3, 0x2b, 0xc6, 0xb8, 0xbd, 0x72, 0x8c, 0xf3, 0x1f, 0x8d, 0x3a, 0x60, 0x17, 0xd5,
	0xd6, 0x9d, 0x65, 0xac, 0xbb, 0x43, 0x68, 0x67, 0x7a, 0xda, 0x39, 0x43, 0xdb, 0x53, 0x07, 0x2c,
	0xf3, 0x5d, 0x1a, 0xcf, 0x6e, 0x70, 0xd0, 0x39, 0x58, 0x66, 0x75, 0xe2, 0x5f, 0x18, 0xf9, 0xa1,
	0x9e, 0xdb, 0x3e, 0x10, 0xfe, 0x8f, 0x05, 0x87, 0x9e, 0x08, 0x44, 0x94, 0xc9, 0xff, 0xfa, 0x4a,
	0xaa, 0xbf, 0x42, 0xec, 0xc6, 0x2b, 0xc4, 0x58, 0x99, 0x4e, 0x73, 0x65, 0x96, 0x6b, 0xa7, 0x55,
	0x5b, 0x3b, 0x27, 0xd0, 0xcb, 0x72, 0xf1, 0x5a, 0x5d, 0xb5, 0xe9, 0xaa, 0x14, 0x60, 0xa2, 0xa2,
	0x24, 0x14, 0x6f, 0x68, 0x04, 0x39, 0x9e, 0x3a, 0x20, 0x57, 0xd5, 0xf6, 0x78, 0x5d, 0x5d, 0x64,
	0x35, 0x59, 0xa3, 0xfc, 0x7a, 0x15, 0x6d, 0x1f, 0x32, 0xab, 0x8c, 0x8d, 0x9e, 0x1a, 0x0e, 0xa5,
	0x3b, 0x4e, 0xc5, 0x1d, 0xfe, 0x0a, 0x0e, 0x57, 0x98, 0x2a, 0xd8, 0x53, 0xe8, 0xe6, 0xfa, 0xf9,
	0x64, 0xd1, 0xf3, 0xe9, 0x78, 0xf5, 0x68, 0xa7, 0x57, 0xd4, 0x02, 0xca, 0xbf, 0xc4, 0x62, 0xdd,
	0xd6, 0x20, 0xe3, 0x64, 0x9a, 0xde, 0xa3, 0xde, 0x7f, 0xd9, 0xf0, 0xbe, 0x27, 0xb2, 0x3a, 0x67,
	0x66, 0x79, 0x2e, 0x12, 0x49, 0x5f, 0x2a, 0x4b, 0x61, 0xd5, 0x4a, 0xf1, 0x7f, 0x7f, 0x0a, 0x9f,
	0x01, 0xab, 0xbe, 0x66, 0x44, 0xe2, 0xc7, 0x72, 0xae, 0x99, 0xb1, 0xe2, 0xc6, 0x20, 0x6d, 0x77,
	0xd3, 0xd3, 0x79, 0xa7, 0xf6, 0x74, 0xe6, 0x23, 0x78, 0x77, 0x55, 0x0d, 0x0a, 0x0c, 0xce, 0xc8,
	0xf6, 0x62, 0xc4, 0x36, 0xe4, 0xfc, 0x07, 0x38, 0xd9, 0x50, 0x85, 0x82, 0x7d, 0x86, 0x64, 0x9a,
	0xa6, 0x0b, 0x72, 0x70, 0x4d, 0x8e, 0x0d, 0x3a, 0x9e, 0x52, 0xe0, 0xe7, 0xe0, 0x9a, 0xee, 0x5d,
	0xce, 0x75, 0xc7, 0xac, 0x29, 0x2e, 0x3f, 0x85, 0xa3, 0xa6, 0x0e, 0xa5, 0x61, 0x41, 0x74, 0xab,
	0x24, 0x3a, 0xff, 0x10, 0x0e, 0x4c, 0x3f, 0xc6, 0xcf, 0x0b, 0xb6, 0x0f, 0xce, 0xf8, 0xf9, 0x22,
	0x62, 0xfc, 0x97, 0xff, 0x04, 0x83, 0xc6, 0x67, 0x69, 0x2b, 0xa0, 0xbf, 0xda, 0xc0, 0x5b, 0xf5,
	0x1c, 0x9f, 0x02, 0xdf, 0x64, 0x41, 0x87, 0xbd, 0xbd, 0x8d, 0x32, 0x41, 0x76, 0x2d, 0x41, 0x5f,
	0x37, 0x9b, 0xa6, 0xb4, 0x53, 0xb0, 0x8f, 0xa1, 0xa3, 0x3a, 0x54, 0x97, 0x6b, 0xe5, 0x4f, 0x21,
	0x0d, 0x99, 0x74, 0xe8, 0xe7, 0xe9, 0x93, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90, 0x50, 0xc3,
	0x44, 0xb5, 0x0e, 0x00, 0x00,
}
