// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomy.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	autonomy.proto
	board.proto
	lcommon.proto
	project.proto
	rule.proto

It has these top-level messages:
	AutonomyAction
	AutonomyProposalBoard
	ProposalBoard
	RevokeProposalBoard
	VoteProposalBoard
	TerminateProposalBoard
	ReceiptProposalBoard
	LocalProposalBoard
	ReqQueryProposalBoard
	ReplyQueryProposalBoard
	VoteResult
	PublicVote
	VotesRecord
	RuleConfig
	AutonomyProposalProject
	ProposalProject
	RevokeProposalProject
	VoteProposalProject
	PubVoteProposalProject
	TerminateProposalProject
	ReceiptProposalProject
	LocalProposalProject
	ReqQueryProposalProject
	ReplyQueryProposalProject
	TransferFund
	AutonomyProposalRule
	ProposalRule
	RevokeProposalRule
	VoteProposalRule
	TerminateProposalRule
	ReceiptProposalRule
	LocalProposalRule
	ReqQueryProposalRule
	ReplyQueryProposalRule
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message for execs.Autonomy
type AutonomyAction struct {
	// Types that are valid to be assigned to Value:
	//	*AutonomyAction_PropBoard
	//	*AutonomyAction_RvkPropBoard
	//	*AutonomyAction_VotePropBoard
	//	*AutonomyAction_TmintPropBoard
	//	*AutonomyAction_PropProject
	//	*AutonomyAction_RvkPropProject
	//	*AutonomyAction_VotePropProject
	//	*AutonomyAction_PubVotePropProject
	//	*AutonomyAction_TmintPropProject
	//	*AutonomyAction_PropRule
	//	*AutonomyAction_RvkPropRule
	//	*AutonomyAction_VotePropRule
	//	*AutonomyAction_TmintPropRule
	//	*AutonomyAction_Transfer
	Value isAutonomyAction_Value `protobuf_oneof:"value"`
	Ty    int32                  `protobuf:"varint,15,opt,name=ty" json:"ty,omitempty"`
}

func (m *AutonomyAction) Reset()                    { *m = AutonomyAction{} }
func (m *AutonomyAction) String() string            { return proto.CompactTextString(m) }
func (*AutonomyAction) ProtoMessage()               {}
func (*AutonomyAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isAutonomyAction_Value interface {
	isAutonomyAction_Value()
}

type AutonomyAction_PropBoard struct {
	PropBoard *ProposalBoard `protobuf:"bytes,1,opt,name=propBoard,oneof"`
}
type AutonomyAction_RvkPropBoard struct {
	RvkPropBoard *RevokeProposalBoard `protobuf:"bytes,2,opt,name=rvkPropBoard,oneof"`
}
type AutonomyAction_VotePropBoard struct {
	VotePropBoard *VoteProposalBoard `protobuf:"bytes,3,opt,name=votePropBoard,oneof"`
}
type AutonomyAction_TmintPropBoard struct {
	TmintPropBoard *TerminateProposalBoard `protobuf:"bytes,4,opt,name=tmintPropBoard,oneof"`
}
type AutonomyAction_PropProject struct {
	PropProject *ProposalProject `protobuf:"bytes,5,opt,name=propProject,oneof"`
}
type AutonomyAction_RvkPropProject struct {
	RvkPropProject *RevokeProposalProject `protobuf:"bytes,6,opt,name=rvkPropProject,oneof"`
}
type AutonomyAction_VotePropProject struct {
	VotePropProject *VoteProposalProject `protobuf:"bytes,7,opt,name=votePropProject,oneof"`
}
type AutonomyAction_PubVotePropProject struct {
	PubVotePropProject *PubVoteProposalProject `protobuf:"bytes,8,opt,name=pubVotePropProject,oneof"`
}
type AutonomyAction_TmintPropProject struct {
	TmintPropProject *TerminateProposalProject `protobuf:"bytes,9,opt,name=tmintPropProject,oneof"`
}
type AutonomyAction_PropRule struct {
	PropRule *ProposalRule `protobuf:"bytes,10,opt,name=propRule,oneof"`
}
type AutonomyAction_RvkPropRule struct {
	RvkPropRule *RevokeProposalRule `protobuf:"bytes,11,opt,name=rvkPropRule,oneof"`
}
type AutonomyAction_VotePropRule struct {
	VotePropRule *VoteProposalRule `protobuf:"bytes,12,opt,name=votePropRule,oneof"`
}
type AutonomyAction_TmintPropRule struct {
	TmintPropRule *TerminateProposalRule `protobuf:"bytes,13,opt,name=tmintPropRule,oneof"`
}
type AutonomyAction_Transfer struct {
	Transfer *TransferFund `protobuf:"bytes,14,opt,name=transfer,oneof"`
}

func (*AutonomyAction_PropBoard) isAutonomyAction_Value()          {}
func (*AutonomyAction_RvkPropBoard) isAutonomyAction_Value()       {}
func (*AutonomyAction_VotePropBoard) isAutonomyAction_Value()      {}
func (*AutonomyAction_TmintPropBoard) isAutonomyAction_Value()     {}
func (*AutonomyAction_PropProject) isAutonomyAction_Value()        {}
func (*AutonomyAction_RvkPropProject) isAutonomyAction_Value()     {}
func (*AutonomyAction_VotePropProject) isAutonomyAction_Value()    {}
func (*AutonomyAction_PubVotePropProject) isAutonomyAction_Value() {}
func (*AutonomyAction_TmintPropProject) isAutonomyAction_Value()   {}
func (*AutonomyAction_PropRule) isAutonomyAction_Value()           {}
func (*AutonomyAction_RvkPropRule) isAutonomyAction_Value()        {}
func (*AutonomyAction_VotePropRule) isAutonomyAction_Value()       {}
func (*AutonomyAction_TmintPropRule) isAutonomyAction_Value()      {}
func (*AutonomyAction_Transfer) isAutonomyAction_Value()           {}

func (m *AutonomyAction) GetValue() isAutonomyAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *AutonomyAction) GetPropBoard() *ProposalBoard {
	if x, ok := m.GetValue().(*AutonomyAction_PropBoard); ok {
		return x.PropBoard
	}
	return nil
}

func (m *AutonomyAction) GetRvkPropBoard() *RevokeProposalBoard {
	if x, ok := m.GetValue().(*AutonomyAction_RvkPropBoard); ok {
		return x.RvkPropBoard
	}
	return nil
}

func (m *AutonomyAction) GetVotePropBoard() *VoteProposalBoard {
	if x, ok := m.GetValue().(*AutonomyAction_VotePropBoard); ok {
		return x.VotePropBoard
	}
	return nil
}

func (m *AutonomyAction) GetTmintPropBoard() *TerminateProposalBoard {
	if x, ok := m.GetValue().(*AutonomyAction_TmintPropBoard); ok {
		return x.TmintPropBoard
	}
	return nil
}

func (m *AutonomyAction) GetPropProject() *ProposalProject {
	if x, ok := m.GetValue().(*AutonomyAction_PropProject); ok {
		return x.PropProject
	}
	return nil
}

func (m *AutonomyAction) GetRvkPropProject() *RevokeProposalProject {
	if x, ok := m.GetValue().(*AutonomyAction_RvkPropProject); ok {
		return x.RvkPropProject
	}
	return nil
}

func (m *AutonomyAction) GetVotePropProject() *VoteProposalProject {
	if x, ok := m.GetValue().(*AutonomyAction_VotePropProject); ok {
		return x.VotePropProject
	}
	return nil
}

func (m *AutonomyAction) GetPubVotePropProject() *PubVoteProposalProject {
	if x, ok := m.GetValue().(*AutonomyAction_PubVotePropProject); ok {
		return x.PubVotePropProject
	}
	return nil
}

func (m *AutonomyAction) GetTmintPropProject() *TerminateProposalProject {
	if x, ok := m.GetValue().(*AutonomyAction_TmintPropProject); ok {
		return x.TmintPropProject
	}
	return nil
}

func (m *AutonomyAction) GetPropRule() *ProposalRule {
	if x, ok := m.GetValue().(*AutonomyAction_PropRule); ok {
		return x.PropRule
	}
	return nil
}

func (m *AutonomyAction) GetRvkPropRule() *RevokeProposalRule {
	if x, ok := m.GetValue().(*AutonomyAction_RvkPropRule); ok {
		return x.RvkPropRule
	}
	return nil
}

func (m *AutonomyAction) GetVotePropRule() *VoteProposalRule {
	if x, ok := m.GetValue().(*AutonomyAction_VotePropRule); ok {
		return x.VotePropRule
	}
	return nil
}

func (m *AutonomyAction) GetTmintPropRule() *TerminateProposalRule {
	if x, ok := m.GetValue().(*AutonomyAction_TmintPropRule); ok {
		return x.TmintPropRule
	}
	return nil
}

func (m *AutonomyAction) GetTransfer() *TransferFund {
	if x, ok := m.GetValue().(*AutonomyAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *AutonomyAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AutonomyAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AutonomyAction_OneofMarshaler, _AutonomyAction_OneofUnmarshaler, _AutonomyAction_OneofSizer, []interface{}{
		(*AutonomyAction_PropBoard)(nil),
		(*AutonomyAction_RvkPropBoard)(nil),
		(*AutonomyAction_VotePropBoard)(nil),
		(*AutonomyAction_TmintPropBoard)(nil),
		(*AutonomyAction_PropProject)(nil),
		(*AutonomyAction_RvkPropProject)(nil),
		(*AutonomyAction_VotePropProject)(nil),
		(*AutonomyAction_PubVotePropProject)(nil),
		(*AutonomyAction_TmintPropProject)(nil),
		(*AutonomyAction_PropRule)(nil),
		(*AutonomyAction_RvkPropRule)(nil),
		(*AutonomyAction_VotePropRule)(nil),
		(*AutonomyAction_TmintPropRule)(nil),
		(*AutonomyAction_Transfer)(nil),
	}
}

func _AutonomyAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AutonomyAction)
	// value
	switch x := m.Value.(type) {
	case *AutonomyAction_PropBoard:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PropBoard); err != nil {
			return err
		}
	case *AutonomyAction_RvkPropBoard:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RvkPropBoard); err != nil {
			return err
		}
	case *AutonomyAction_VotePropBoard:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VotePropBoard); err != nil {
			return err
		}
	case *AutonomyAction_TmintPropBoard:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TmintPropBoard); err != nil {
			return err
		}
	case *AutonomyAction_PropProject:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PropProject); err != nil {
			return err
		}
	case *AutonomyAction_RvkPropProject:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RvkPropProject); err != nil {
			return err
		}
	case *AutonomyAction_VotePropProject:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VotePropProject); err != nil {
			return err
		}
	case *AutonomyAction_PubVotePropProject:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PubVotePropProject); err != nil {
			return err
		}
	case *AutonomyAction_TmintPropProject:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TmintPropProject); err != nil {
			return err
		}
	case *AutonomyAction_PropRule:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PropRule); err != nil {
			return err
		}
	case *AutonomyAction_RvkPropRule:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RvkPropRule); err != nil {
			return err
		}
	case *AutonomyAction_VotePropRule:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VotePropRule); err != nil {
			return err
		}
	case *AutonomyAction_TmintPropRule:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TmintPropRule); err != nil {
			return err
		}
	case *AutonomyAction_Transfer:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Transfer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AutonomyAction.Value has unexpected type %T", x)
	}
	return nil
}

func _AutonomyAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AutonomyAction)
	switch tag {
	case 1: // value.propBoard
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProposalBoard)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_PropBoard{msg}
		return true, err
	case 2: // value.rvkPropBoard
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeProposalBoard)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_RvkPropBoard{msg}
		return true, err
	case 3: // value.votePropBoard
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VoteProposalBoard)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_VotePropBoard{msg}
		return true, err
	case 4: // value.tmintPropBoard
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TerminateProposalBoard)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_TmintPropBoard{msg}
		return true, err
	case 5: // value.propProject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProposalProject)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_PropProject{msg}
		return true, err
	case 6: // value.rvkPropProject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeProposalProject)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_RvkPropProject{msg}
		return true, err
	case 7: // value.votePropProject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VoteProposalProject)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_VotePropProject{msg}
		return true, err
	case 8: // value.pubVotePropProject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PubVoteProposalProject)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_PubVotePropProject{msg}
		return true, err
	case 9: // value.tmintPropProject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TerminateProposalProject)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_TmintPropProject{msg}
		return true, err
	case 10: // value.propRule
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProposalRule)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_PropRule{msg}
		return true, err
	case 11: // value.rvkPropRule
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeProposalRule)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_RvkPropRule{msg}
		return true, err
	case 12: // value.votePropRule
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VoteProposalRule)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_VotePropRule{msg}
		return true, err
	case 13: // value.tmintPropRule
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TerminateProposalRule)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_TmintPropRule{msg}
		return true, err
	case 14: // value.transfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransferFund)
		err := b.DecodeMessage(msg)
		m.Value = &AutonomyAction_Transfer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AutonomyAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AutonomyAction)
	// value
	switch x := m.Value.(type) {
	case *AutonomyAction_PropBoard:
		s := proto.Size(x.PropBoard)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_RvkPropBoard:
		s := proto.Size(x.RvkPropBoard)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_VotePropBoard:
		s := proto.Size(x.VotePropBoard)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_TmintPropBoard:
		s := proto.Size(x.TmintPropBoard)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_PropProject:
		s := proto.Size(x.PropProject)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_RvkPropProject:
		s := proto.Size(x.RvkPropProject)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_VotePropProject:
		s := proto.Size(x.VotePropProject)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_PubVotePropProject:
		s := proto.Size(x.PubVotePropProject)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_TmintPropProject:
		s := proto.Size(x.TmintPropProject)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_PropRule:
		s := proto.Size(x.PropRule)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_RvkPropRule:
		s := proto.Size(x.RvkPropRule)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_VotePropRule:
		s := proto.Size(x.VotePropRule)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_TmintPropRule:
		s := proto.Size(x.TmintPropRule)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AutonomyAction_Transfer:
		s := proto.Size(x.Transfer)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*AutonomyAction)(nil), "types.AutonomyAction")
}

func init() { proto.RegisterFile("autonomy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4b, 0x6b, 0xf2, 0x40,
	0x14, 0x40, 0xd5, 0xef, 0x8b, 0x8f, 0x1b, 0x13, 0xcb, 0x6d, 0x69, 0x53, 0x69, 0xa9, 0x74, 0xe5,
	0x4a, 0xe8, 0x63, 0x55, 0x10, 0x54, 0x8a, 0x75, 0x53, 0x1a, 0x82, 0xb8, 0x8f, 0x76, 0x0a, 0xd6,
	0x98, 0x09, 0xe3, 0x24, 0x90, 0xbf, 0xd7, 0x5f, 0x56, 0x32, 0x4e, 0x1e, 0x13, 0xd3, 0x9d, 0xe6,
	0xde, 0x73, 0xe0, 0x1e, 0x0d, 0x98, 0x6e, 0xc8, 0xa9, 0x4f, 0xf7, 0xf1, 0x28, 0x60, 0x94, 0x53,
	0xd4, 0x78, 0x1c, 0x90, 0x43, 0x5f, 0x5f, 0x53, 0x97, 0x7d, 0x1e, 0x9f, 0xf5, 0x8d, 0x80, 0xd1,
	0x6f, 0xb2, 0xe1, 0xf2, 0x2b, 0xb0, 0xd0, 0x23, 0xc7, 0xcf, 0xf7, 0x3f, 0x2d, 0x30, 0xa7, 0xd2,
	0x30, 0xdd, 0xf0, 0x2d, 0xf5, 0xf1, 0x19, 0x3a, 0x01, 0xa3, 0xc1, 0x2c, 0x11, 0x58, 0xf5, 0x41,
	0x7d, 0xa8, 0x3f, 0x5e, 0x8c, 0x84, 0x75, 0x64, 0x33, 0x1a, 0xd0, 0x83, 0xeb, 0x89, 0xd9, 0xa2,
	0xe6, 0xe4, 0x8b, 0x38, 0x81, 0x2e, 0x8b, 0x76, 0x76, 0x06, 0x36, 0x04, 0xd8, 0x97, 0xa0, 0x43,
	0x22, 0xba, 0x23, 0x65, 0x5c, 0x21, 0x70, 0x02, 0x46, 0x44, 0x39, 0xc9, 0x15, 0xff, 0x84, 0xc2,
	0x92, 0x8a, 0x95, 0x9c, 0x15, 0x05, 0x2a, 0x80, 0x6f, 0x60, 0xf2, 0xfd, 0xd6, 0xe7, 0xb9, 0xe2,
	0xbf, 0x50, 0xdc, 0x4a, 0xc5, 0x92, 0xb0, 0xfd, 0xd6, 0x77, 0x4f, 0x3d, 0x25, 0x0c, 0x5f, 0x40,
	0x4f, 0x2e, 0xb3, 0x8f, 0xd9, 0x2c, 0x4d, 0x58, 0x2e, 0x4b, 0x11, 0xe4, 0x74, 0x51, 0x73, 0x8a,
	0xcb, 0x38, 0x07, 0x53, 0x9e, 0x95, 0xe2, 0x4d, 0x81, 0xdf, 0x54, 0xa6, 0xc8, 0x25, 0x25, 0x0a,
	0xe7, 0xd0, 0x4b, 0xaf, 0x4b, 0x45, 0x2d, 0xa5, 0x69, 0x31, 0x48, 0xae, 0x29, 0x43, 0xf8, 0x01,
	0x18, 0x84, 0xeb, 0x55, 0x49, 0xd5, 0x56, 0xc2, 0xd8, 0xf9, 0x82, 0x6a, 0xab, 0x40, 0xf1, 0x1d,
	0xce, 0xb2, 0x5c, 0xa9, 0xae, 0x23, 0x74, 0x77, 0x7f, 0x75, 0xce, 0x85, 0x27, 0x28, 0x3e, 0x40,
	0x3b, 0xc9, 0xe7, 0x84, 0x1e, 0xb1, 0x40, 0x68, 0xce, 0x4b, 0xa1, 0x93, 0xd1, 0xa2, 0xe6, 0x64,
	0x6b, 0x38, 0x06, 0x5d, 0xc6, 0x12, 0x94, 0x2e, 0xa8, 0xeb, 0xca, 0xbe, 0x92, 0x2d, 0xee, 0xe3,
	0x18, 0xba, 0x69, 0x24, 0xc1, 0x77, 0x05, 0x7f, 0x55, 0x91, 0x55, 0xd2, 0xca, 0x3a, 0xbe, 0x82,
	0x91, 0x1d, 0x21, 0x78, 0x43, 0xf9, 0x7d, 0x4f, 0x8e, 0x97, 0x12, 0x15, 0x4a, 0xce, 0xe6, 0xcc,
	0xf5, 0x0f, 0x5f, 0x84, 0x59, 0xa6, 0x72, 0xf6, 0x52, 0x3e, 0x9e, 0x87, 0x7e, 0xf2, 0xdf, 0xcc,
	0xd6, 0xd0, 0x84, 0x06, 0x8f, 0xad, 0xde, 0xa0, 0x3e, 0xd4, 0x9c, 0x06, 0x8f, 0x67, 0x2d, 0xd0,
	0x22, 0xd7, 0x0b, 0xc9, 0xba, 0x29, 0xde, 0xe5, 0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95,
	0x75, 0xd2, 0x7a, 0x0c, 0x04, 0x00, 0x00,
}
