syntax = "proto3";

package types;
option go_package = "../types";

message RgbxAction {
  int32 ty = 1;
  oneof value {
    mintAsset mint = 2;
    transferAsset transfer = 3;
    confirmTx confirm = 4;
  }
}

message rgbxAsset {

  uint32 type = 1;
  uint32 precision = 2;
  int64 totalAmount = 3;
  string symbol = 4;
  bytes metaHash = 5;
  string genesisBtcTxHash = 6;
  string owner = 7;
}


message mintAsset {
  uint32 type = 1;
  uint32 precision = 2;
  int64 totalAmount = 3;
  string symbol = 4;
  bytes metaHash =5;
  // represents the outpoint of the transaction's
  // input that resulted in the creation of the asset.
  outPoint genesisOut = 6;
}

message outPoint {
  string hash = 1;
  uint32 index = 2;
  bytes pkScript = 3;
}


message utxoSpendingProof {
  uint32 spendingInputIdx = 1;
  int32 opRetOutputIdx =2;
  bytes spendingTx = 3;
  bytes opRetOutputPkScript = 4;
}

message transferAsset {

  string  symbol = 1;
  int64   amount = 2;
  string  from = 3;
  string  to = 4;
  string  changeAddr = 5;
  bytes   fromPkScript = 6;
}

message confirmTx {

  int32 actionType = 1;
  int64 confirmedBlockHeight = 2;
  int64 txBlockHeight = 3;
  int64 txIndex = 4;
  bytes txHash = 5;
  bool timeout = 6;
  utxoSpendingProof proof =7;
}


message pendingTx {
  int32 actionType = 1;
  int64 timestamp = 2;
  int64 txBlockHeight = 3;
  int64 txIndex = 4;
  bytes txHash = 5;
  outPoint utxo = 6;
  bool confirmed = 7;
}

message pendingTxs {
  repeated pendingTx pendingList=1;
}

message ReqListPendingTx {
  int64 startHeight = 1;
  int64 startIndex = 2;
  int32 count = 3;
}


message ReqGetPendingTx {
  int64 height = 1;
  int64 index = 2;
}

service rgbx {

}

