// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paracross.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	types "github.com/33cn/chain33/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// stateDB
type ParacrossStatusDetails struct {
	Addrs                []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	BlockHash            [][]byte `protobuf:"bytes,2,rep,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossStatusDetails) Reset()         { *m = ParacrossStatusDetails{} }
func (m *ParacrossStatusDetails) String() string { return proto.CompactTextString(m) }
func (*ParacrossStatusDetails) ProtoMessage()    {}
func (*ParacrossStatusDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{0}
}

func (m *ParacrossStatusDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossStatusDetails.Unmarshal(m, b)
}
func (m *ParacrossStatusDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossStatusDetails.Marshal(b, m, deterministic)
}
func (m *ParacrossStatusDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossStatusDetails.Merge(m, src)
}
func (m *ParacrossStatusDetails) XXX_Size() int {
	return xxx_messageInfo_ParacrossStatusDetails.Size(m)
}
func (m *ParacrossStatusDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossStatusDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossStatusDetails proto.InternalMessageInfo

func (m *ParacrossStatusDetails) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *ParacrossStatusDetails) GetBlockHash() [][]byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type ParacrossHeightStatus struct {
	// ing, done
	Status               int32                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Title                string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Height               int64                   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Details              *ParacrossStatusDetails `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ParacrossHeightStatus) Reset()         { *m = ParacrossHeightStatus{} }
func (m *ParacrossHeightStatus) String() string { return proto.CompactTextString(m) }
func (*ParacrossHeightStatus) ProtoMessage()    {}
func (*ParacrossHeightStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{1}
}

func (m *ParacrossHeightStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossHeightStatus.Unmarshal(m, b)
}
func (m *ParacrossHeightStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossHeightStatus.Marshal(b, m, deterministic)
}
func (m *ParacrossHeightStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossHeightStatus.Merge(m, src)
}
func (m *ParacrossHeightStatus) XXX_Size() int {
	return xxx_messageInfo_ParacrossHeightStatus.Size(m)
}
func (m *ParacrossHeightStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossHeightStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossHeightStatus proto.InternalMessageInfo

func (m *ParacrossHeightStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ParacrossHeightStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossHeightStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossHeightStatus) GetDetails() *ParacrossStatusDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

type ParacrossStatus struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossStatus) Reset()         { *m = ParacrossStatus{} }
func (m *ParacrossStatus) String() string { return proto.CompactTextString(m) }
func (*ParacrossStatus) ProtoMessage()    {}
func (*ParacrossStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{2}
}

func (m *ParacrossStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossStatus.Unmarshal(m, b)
}
func (m *ParacrossStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossStatus.Marshal(b, m, deterministic)
}
func (m *ParacrossStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossStatus.Merge(m, src)
}
func (m *ParacrossStatus) XXX_Size() int {
	return xxx_messageInfo_ParacrossStatus.Size(m)
}
func (m *ParacrossStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossStatus proto.InternalMessageInfo

func (m *ParacrossStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossStatus) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type ParacrossConsensusStatus struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ChainHeight          int64    `protobuf:"varint,2,opt,name=chainHeight,proto3" json:"chainHeight,omitempty"`
	ConsensHeight        int64    `protobuf:"varint,3,opt,name=consensHeight,proto3" json:"consensHeight,omitempty"`
	ConsensBlockHash     string   `protobuf:"bytes,4,opt,name=consensBlockHash,proto3" json:"consensBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossConsensusStatus) Reset()         { *m = ParacrossConsensusStatus{} }
func (m *ParacrossConsensusStatus) String() string { return proto.CompactTextString(m) }
func (*ParacrossConsensusStatus) ProtoMessage()    {}
func (*ParacrossConsensusStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{3}
}

func (m *ParacrossConsensusStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossConsensusStatus.Unmarshal(m, b)
}
func (m *ParacrossConsensusStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossConsensusStatus.Marshal(b, m, deterministic)
}
func (m *ParacrossConsensusStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossConsensusStatus.Merge(m, src)
}
func (m *ParacrossConsensusStatus) XXX_Size() int {
	return xxx_messageInfo_ParacrossConsensusStatus.Size(m)
}
func (m *ParacrossConsensusStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossConsensusStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossConsensusStatus proto.InternalMessageInfo

func (m *ParacrossConsensusStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossConsensusStatus) GetChainHeight() int64 {
	if m != nil {
		return m.ChainHeight
	}
	return 0
}

func (m *ParacrossConsensusStatus) GetConsensHeight() int64 {
	if m != nil {
		return m.ConsensHeight
	}
	return 0
}

func (m *ParacrossConsensusStatus) GetConsensBlockHash() string {
	if m != nil {
		return m.ConsensBlockHash
	}
	return ""
}

type ParaBlock2MainMap struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	MainHeight           int64    `protobuf:"varint,3,opt,name=mainHeight,proto3" json:"mainHeight,omitempty"`
	MainHash             string   `protobuf:"bytes,4,opt,name=mainHash,proto3" json:"mainHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParaBlock2MainMap) Reset()         { *m = ParaBlock2MainMap{} }
func (m *ParaBlock2MainMap) String() string { return proto.CompactTextString(m) }
func (*ParaBlock2MainMap) ProtoMessage()    {}
func (*ParaBlock2MainMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{4}
}

func (m *ParaBlock2MainMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParaBlock2MainMap.Unmarshal(m, b)
}
func (m *ParaBlock2MainMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParaBlock2MainMap.Marshal(b, m, deterministic)
}
func (m *ParaBlock2MainMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParaBlock2MainMap.Merge(m, src)
}
func (m *ParaBlock2MainMap) XXX_Size() int {
	return xxx_messageInfo_ParaBlock2MainMap.Size(m)
}
func (m *ParaBlock2MainMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ParaBlock2MainMap.DiscardUnknown(m)
}

var xxx_messageInfo_ParaBlock2MainMap proto.InternalMessageInfo

func (m *ParaBlock2MainMap) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParaBlock2MainMap) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *ParaBlock2MainMap) GetMainHeight() int64 {
	if m != nil {
		return m.MainHeight
	}
	return 0
}

func (m *ParaBlock2MainMap) GetMainHash() string {
	if m != nil {
		return m.MainHash
	}
	return ""
}

type ParaBlock2MainInfo struct {
	Items                []*ParaBlock2MainMap `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ParaBlock2MainInfo) Reset()         { *m = ParaBlock2MainInfo{} }
func (m *ParaBlock2MainInfo) String() string { return proto.CompactTextString(m) }
func (*ParaBlock2MainInfo) ProtoMessage()    {}
func (*ParaBlock2MainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{5}
}

func (m *ParaBlock2MainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParaBlock2MainInfo.Unmarshal(m, b)
}
func (m *ParaBlock2MainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParaBlock2MainInfo.Marshal(b, m, deterministic)
}
func (m *ParaBlock2MainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParaBlock2MainInfo.Merge(m, src)
}
func (m *ParaBlock2MainInfo) XXX_Size() int {
	return xxx_messageInfo_ParaBlock2MainInfo.Size(m)
}
func (m *ParaBlock2MainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ParaBlock2MainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ParaBlock2MainInfo proto.InternalMessageInfo

func (m *ParaBlock2MainInfo) GetItems() []*ParaBlock2MainMap {
	if m != nil {
		return m.Items
	}
	return nil
}

// action
type ParacrossNodeStatus struct {
	MainBlockHash        []byte   `protobuf:"bytes,1,opt,name=mainBlockHash,proto3" json:"mainBlockHash,omitempty"`
	MainBlockHeight      int64    `protobuf:"varint,2,opt,name=mainBlockHeight,proto3" json:"mainBlockHeight,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Height               int64    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	PreBlockHash         []byte   `protobuf:"bytes,5,opt,name=preBlockHash,proto3" json:"preBlockHash,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,6,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	PreStateHash         []byte   `protobuf:"bytes,7,opt,name=preStateHash,proto3" json:"preStateHash,omitempty"`
	StateHash            []byte   `protobuf:"bytes,8,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	TxCounts             uint32   `protobuf:"varint,9,opt,name=txCounts,proto3" json:"txCounts,omitempty"`
	TxResult             []byte   `protobuf:"bytes,10,opt,name=txResult,proto3" json:"txResult,omitempty"`
	TxHashs              [][]byte `protobuf:"bytes,11,rep,name=txHashs,proto3" json:"txHashs,omitempty"`
	CrossTxResult        []byte   `protobuf:"bytes,12,opt,name=crossTxResult,proto3" json:"crossTxResult,omitempty"`
	CrossTxHashs         [][]byte `protobuf:"bytes,13,rep,name=crossTxHashs,proto3" json:"crossTxHashs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossNodeStatus) Reset()         { *m = ParacrossNodeStatus{} }
func (m *ParacrossNodeStatus) String() string { return proto.CompactTextString(m) }
func (*ParacrossNodeStatus) ProtoMessage()    {}
func (*ParacrossNodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{6}
}

func (m *ParacrossNodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossNodeStatus.Unmarshal(m, b)
}
func (m *ParacrossNodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossNodeStatus.Marshal(b, m, deterministic)
}
func (m *ParacrossNodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossNodeStatus.Merge(m, src)
}
func (m *ParacrossNodeStatus) XXX_Size() int {
	return xxx_messageInfo_ParacrossNodeStatus.Size(m)
}
func (m *ParacrossNodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossNodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossNodeStatus proto.InternalMessageInfo

func (m *ParacrossNodeStatus) GetMainBlockHash() []byte {
	if m != nil {
		return m.MainBlockHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetMainBlockHeight() int64 {
	if m != nil {
		return m.MainBlockHeight
	}
	return 0
}

func (m *ParacrossNodeStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossNodeStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossNodeStatus) GetPreBlockHash() []byte {
	if m != nil {
		return m.PreBlockHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetPreStateHash() []byte {
	if m != nil {
		return m.PreStateHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetTxCounts() uint32 {
	if m != nil {
		return m.TxCounts
	}
	return 0
}

func (m *ParacrossNodeStatus) GetTxResult() []byte {
	if m != nil {
		return m.TxResult
	}
	return nil
}

func (m *ParacrossNodeStatus) GetTxHashs() [][]byte {
	if m != nil {
		return m.TxHashs
	}
	return nil
}

func (m *ParacrossNodeStatus) GetCrossTxResult() []byte {
	if m != nil {
		return m.CrossTxResult
	}
	return nil
}

func (m *ParacrossNodeStatus) GetCrossTxHashs() [][]byte {
	if m != nil {
		return m.CrossTxHashs
	}
	return nil
}

type ParacrossCommitAction struct {
	Status               *ParacrossNodeStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ParacrossCommitAction) Reset()         { *m = ParacrossCommitAction{} }
func (m *ParacrossCommitAction) String() string { return proto.CompactTextString(m) }
func (*ParacrossCommitAction) ProtoMessage()    {}
func (*ParacrossCommitAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{7}
}

func (m *ParacrossCommitAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossCommitAction.Unmarshal(m, b)
}
func (m *ParacrossCommitAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossCommitAction.Marshal(b, m, deterministic)
}
func (m *ParacrossCommitAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossCommitAction.Merge(m, src)
}
func (m *ParacrossCommitAction) XXX_Size() int {
	return xxx_messageInfo_ParacrossCommitAction.Size(m)
}
func (m *ParacrossCommitAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossCommitAction.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossCommitAction proto.InternalMessageInfo

func (m *ParacrossCommitAction) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ParacrossMinerAction struct {
	Status               *ParacrossNodeStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ParacrossMinerAction) Reset()         { *m = ParacrossMinerAction{} }
func (m *ParacrossMinerAction) String() string { return proto.CompactTextString(m) }
func (*ParacrossMinerAction) ProtoMessage()    {}
func (*ParacrossMinerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{8}
}

func (m *ParacrossMinerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossMinerAction.Unmarshal(m, b)
}
func (m *ParacrossMinerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossMinerAction.Marshal(b, m, deterministic)
}
func (m *ParacrossMinerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossMinerAction.Merge(m, src)
}
func (m *ParacrossMinerAction) XXX_Size() int {
	return xxx_messageInfo_ParacrossMinerAction.Size(m)
}
func (m *ParacrossMinerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossMinerAction.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossMinerAction proto.InternalMessageInfo

func (m *ParacrossMinerAction) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ParacrossAction struct {
	// Types that are valid to be assigned to Value:
	//	*ParacrossAction_Commit
	//	*ParacrossAction_Miner
	//	*ParacrossAction_AssetTransfer
	//	*ParacrossAction_AssetWithdraw
	//	*ParacrossAction_Transfer
	//	*ParacrossAction_Withdraw
	//	*ParacrossAction_TransferToExec
	Value                isParacrossAction_Value `protobuf_oneof:"value"`
	Ty                   int32                   `protobuf:"varint,2,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ParacrossAction) Reset()         { *m = ParacrossAction{} }
func (m *ParacrossAction) String() string { return proto.CompactTextString(m) }
func (*ParacrossAction) ProtoMessage()    {}
func (*ParacrossAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{9}
}

func (m *ParacrossAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossAction.Unmarshal(m, b)
}
func (m *ParacrossAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossAction.Marshal(b, m, deterministic)
}
func (m *ParacrossAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossAction.Merge(m, src)
}
func (m *ParacrossAction) XXX_Size() int {
	return xxx_messageInfo_ParacrossAction.Size(m)
}
func (m *ParacrossAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossAction.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossAction proto.InternalMessageInfo

type isParacrossAction_Value interface {
	isParacrossAction_Value()
}

type ParacrossAction_Commit struct {
	Commit *ParacrossCommitAction `protobuf:"bytes,1,opt,name=commit,proto3,oneof"`
}

type ParacrossAction_Miner struct {
	Miner *ParacrossMinerAction `protobuf:"bytes,3,opt,name=miner,proto3,oneof"`
}

type ParacrossAction_AssetTransfer struct {
	AssetTransfer *types.AssetsTransfer `protobuf:"bytes,4,opt,name=assetTransfer,proto3,oneof"`
}

type ParacrossAction_AssetWithdraw struct {
	AssetWithdraw *types.AssetsWithdraw `protobuf:"bytes,5,opt,name=assetWithdraw,proto3,oneof"`
}

type ParacrossAction_Transfer struct {
	Transfer *types.AssetsTransfer `protobuf:"bytes,6,opt,name=transfer,proto3,oneof"`
}

type ParacrossAction_Withdraw struct {
	Withdraw *types.AssetsWithdraw `protobuf:"bytes,7,opt,name=withdraw,proto3,oneof"`
}

type ParacrossAction_TransferToExec struct {
	TransferToExec *types.AssetsTransferToExec `protobuf:"bytes,8,opt,name=transferToExec,proto3,oneof"`
}

func (*ParacrossAction_Commit) isParacrossAction_Value() {}

func (*ParacrossAction_Miner) isParacrossAction_Value() {}

func (*ParacrossAction_AssetTransfer) isParacrossAction_Value() {}

func (*ParacrossAction_AssetWithdraw) isParacrossAction_Value() {}

func (*ParacrossAction_Transfer) isParacrossAction_Value() {}

func (*ParacrossAction_Withdraw) isParacrossAction_Value() {}

func (*ParacrossAction_TransferToExec) isParacrossAction_Value() {}

func (m *ParacrossAction) GetValue() isParacrossAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ParacrossAction) GetCommit() *ParacrossCommitAction {
	if x, ok := m.GetValue().(*ParacrossAction_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *ParacrossAction) GetMiner() *ParacrossMinerAction {
	if x, ok := m.GetValue().(*ParacrossAction_Miner); ok {
		return x.Miner
	}
	return nil
}

func (m *ParacrossAction) GetAssetTransfer() *types.AssetsTransfer {
	if x, ok := m.GetValue().(*ParacrossAction_AssetTransfer); ok {
		return x.AssetTransfer
	}
	return nil
}

func (m *ParacrossAction) GetAssetWithdraw() *types.AssetsWithdraw {
	if x, ok := m.GetValue().(*ParacrossAction_AssetWithdraw); ok {
		return x.AssetWithdraw
	}
	return nil
}

func (m *ParacrossAction) GetTransfer() *types.AssetsTransfer {
	if x, ok := m.GetValue().(*ParacrossAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *ParacrossAction) GetWithdraw() *types.AssetsWithdraw {
	if x, ok := m.GetValue().(*ParacrossAction_Withdraw); ok {
		return x.Withdraw
	}
	return nil
}

func (m *ParacrossAction) GetTransferToExec() *types.AssetsTransferToExec {
	if x, ok := m.GetValue().(*ParacrossAction_TransferToExec); ok {
		return x.TransferToExec
	}
	return nil
}

func (m *ParacrossAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ParacrossAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ParacrossAction_OneofMarshaler, _ParacrossAction_OneofUnmarshaler, _ParacrossAction_OneofSizer, []interface{}{
		(*ParacrossAction_Commit)(nil),
		(*ParacrossAction_Miner)(nil),
		(*ParacrossAction_AssetTransfer)(nil),
		(*ParacrossAction_AssetWithdraw)(nil),
		(*ParacrossAction_Transfer)(nil),
		(*ParacrossAction_Withdraw)(nil),
		(*ParacrossAction_TransferToExec)(nil),
	}
}

func _ParacrossAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ParacrossAction)
	// value
	switch x := m.Value.(type) {
	case *ParacrossAction_Commit:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case *ParacrossAction_Miner:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Miner); err != nil {
			return err
		}
	case *ParacrossAction_AssetTransfer:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AssetTransfer); err != nil {
			return err
		}
	case *ParacrossAction_AssetWithdraw:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AssetWithdraw); err != nil {
			return err
		}
	case *ParacrossAction_Transfer:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Transfer); err != nil {
			return err
		}
	case *ParacrossAction_Withdraw:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Withdraw); err != nil {
			return err
		}
	case *ParacrossAction_TransferToExec:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TransferToExec); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ParacrossAction.Value has unexpected type %T", x)
	}
	return nil
}

func _ParacrossAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ParacrossAction)
	switch tag {
	case 1: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ParacrossCommitAction)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_Commit{msg}
		return true, err
	case 3: // value.miner
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ParacrossMinerAction)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_Miner{msg}
		return true, err
	case 4: // value.assetTransfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(types.AssetsTransfer)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_AssetTransfer{msg}
		return true, err
	case 5: // value.assetWithdraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(types.AssetsWithdraw)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_AssetWithdraw{msg}
		return true, err
	case 6: // value.transfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(types.AssetsTransfer)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_Transfer{msg}
		return true, err
	case 7: // value.withdraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(types.AssetsWithdraw)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_Withdraw{msg}
		return true, err
	case 8: // value.transferToExec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(types.AssetsTransferToExec)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_TransferToExec{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ParacrossAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ParacrossAction)
	// value
	switch x := m.Value.(type) {
	case *ParacrossAction_Commit:
		s := proto.Size(x.Commit)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_Miner:
		s := proto.Size(x.Miner)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_AssetTransfer:
		s := proto.Size(x.AssetTransfer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_AssetWithdraw:
		s := proto.Size(x.AssetWithdraw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_Transfer:
		s := proto.Size(x.Transfer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_Withdraw:
		s := proto.Size(x.Withdraw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ParacrossAction_TransferToExec:
		s := proto.Size(x.TransferToExec)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// logs
type ReceiptParacrossCommit struct {
	Addr                 string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               *ParacrossNodeStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Prev                 *ParacrossHeightStatus `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Current              *ParacrossHeightStatus `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReceiptParacrossCommit) Reset()         { *m = ReceiptParacrossCommit{} }
func (m *ReceiptParacrossCommit) String() string { return proto.CompactTextString(m) }
func (*ReceiptParacrossCommit) ProtoMessage()    {}
func (*ReceiptParacrossCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{10}
}

func (m *ReceiptParacrossCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptParacrossCommit.Unmarshal(m, b)
}
func (m *ReceiptParacrossCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptParacrossCommit.Marshal(b, m, deterministic)
}
func (m *ReceiptParacrossCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptParacrossCommit.Merge(m, src)
}
func (m *ReceiptParacrossCommit) XXX_Size() int {
	return xxx_messageInfo_ReceiptParacrossCommit.Size(m)
}
func (m *ReceiptParacrossCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptParacrossCommit.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptParacrossCommit proto.InternalMessageInfo

func (m *ReceiptParacrossCommit) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptParacrossCommit) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReceiptParacrossCommit) GetPrev() *ParacrossHeightStatus {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *ReceiptParacrossCommit) GetCurrent() *ParacrossHeightStatus {
	if m != nil {
		return m.Current
	}
	return nil
}

type ReceiptParacrossMiner struct {
	Status               *ParacrossNodeStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReceiptParacrossMiner) Reset()         { *m = ReceiptParacrossMiner{} }
func (m *ReceiptParacrossMiner) String() string { return proto.CompactTextString(m) }
func (*ReceiptParacrossMiner) ProtoMessage()    {}
func (*ReceiptParacrossMiner) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{11}
}

func (m *ReceiptParacrossMiner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptParacrossMiner.Unmarshal(m, b)
}
func (m *ReceiptParacrossMiner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptParacrossMiner.Marshal(b, m, deterministic)
}
func (m *ReceiptParacrossMiner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptParacrossMiner.Merge(m, src)
}
func (m *ReceiptParacrossMiner) XXX_Size() int {
	return xxx_messageInfo_ReceiptParacrossMiner.Size(m)
}
func (m *ReceiptParacrossMiner) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptParacrossMiner.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptParacrossMiner proto.InternalMessageInfo

func (m *ReceiptParacrossMiner) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReceiptParacrossDone struct {
	TotalNodes           int32    `protobuf:"varint,1,opt,name=totalNodes,proto3" json:"totalNodes,omitempty"`
	TotalCommit          int32    `protobuf:"varint,2,opt,name=totalCommit,proto3" json:"totalCommit,omitempty"`
	MostSameCommit       int32    `protobuf:"varint,3,opt,name=mostSameCommit,proto3" json:"mostSameCommit,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Height               int64    `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	StateHash            []byte   `protobuf:"bytes,6,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	TxCounts             uint32   `protobuf:"varint,7,opt,name=txCounts,proto3" json:"txCounts,omitempty"`
	TxResult             []byte   `protobuf:"bytes,8,opt,name=txResult,proto3" json:"txResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptParacrossDone) Reset()         { *m = ReceiptParacrossDone{} }
func (m *ReceiptParacrossDone) String() string { return proto.CompactTextString(m) }
func (*ReceiptParacrossDone) ProtoMessage()    {}
func (*ReceiptParacrossDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{12}
}

func (m *ReceiptParacrossDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptParacrossDone.Unmarshal(m, b)
}
func (m *ReceiptParacrossDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptParacrossDone.Marshal(b, m, deterministic)
}
func (m *ReceiptParacrossDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptParacrossDone.Merge(m, src)
}
func (m *ReceiptParacrossDone) XXX_Size() int {
	return xxx_messageInfo_ReceiptParacrossDone.Size(m)
}
func (m *ReceiptParacrossDone) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptParacrossDone.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptParacrossDone proto.InternalMessageInfo

func (m *ReceiptParacrossDone) GetTotalNodes() int32 {
	if m != nil {
		return m.TotalNodes
	}
	return 0
}

func (m *ReceiptParacrossDone) GetTotalCommit() int32 {
	if m != nil {
		return m.TotalCommit
	}
	return 0
}

func (m *ReceiptParacrossDone) GetMostSameCommit() int32 {
	if m != nil {
		return m.MostSameCommit
	}
	return 0
}

func (m *ReceiptParacrossDone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReceiptParacrossDone) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReceiptParacrossDone) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *ReceiptParacrossDone) GetTxCounts() uint32 {
	if m != nil {
		return m.TxCounts
	}
	return 0
}

func (m *ReceiptParacrossDone) GetTxResult() []byte {
	if m != nil {
		return m.TxResult
	}
	return nil
}

type ReceiptParacrossRecord struct {
	Addr                 string               `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               *ParacrossNodeStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReceiptParacrossRecord) Reset()         { *m = ReceiptParacrossRecord{} }
func (m *ReceiptParacrossRecord) String() string { return proto.CompactTextString(m) }
func (*ReceiptParacrossRecord) ProtoMessage()    {}
func (*ReceiptParacrossRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{13}
}

func (m *ReceiptParacrossRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptParacrossRecord.Unmarshal(m, b)
}
func (m *ReceiptParacrossRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptParacrossRecord.Marshal(b, m, deterministic)
}
func (m *ReceiptParacrossRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptParacrossRecord.Merge(m, src)
}
func (m *ReceiptParacrossRecord) XXX_Size() int {
	return xxx_messageInfo_ReceiptParacrossRecord.Size(m)
}
func (m *ReceiptParacrossRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptParacrossRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptParacrossRecord proto.InternalMessageInfo

func (m *ReceiptParacrossRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptParacrossRecord) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// LocalDB
// title-height-addr : txHash
type ParacrossTx struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossTx) Reset()         { *m = ParacrossTx{} }
func (m *ParacrossTx) String() string { return proto.CompactTextString(m) }
func (*ParacrossTx) ProtoMessage()    {}
func (*ParacrossTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{14}
}

func (m *ParacrossTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossTx.Unmarshal(m, b)
}
func (m *ParacrossTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossTx.Marshal(b, m, deterministic)
}
func (m *ParacrossTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossTx.Merge(m, src)
}
func (m *ParacrossTx) XXX_Size() int {
	return xxx_messageInfo_ParacrossTx.Size(m)
}
func (m *ParacrossTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossTx.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossTx proto.InternalMessageInfo

func (m *ParacrossTx) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// query
type ReqParacrossTitleHeight struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqParacrossTitleHeight) Reset()         { *m = ReqParacrossTitleHeight{} }
func (m *ReqParacrossTitleHeight) String() string { return proto.CompactTextString(m) }
func (*ReqParacrossTitleHeight) ProtoMessage()    {}
func (*ReqParacrossTitleHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{15}
}

func (m *ReqParacrossTitleHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqParacrossTitleHeight.Unmarshal(m, b)
}
func (m *ReqParacrossTitleHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqParacrossTitleHeight.Marshal(b, m, deterministic)
}
func (m *ReqParacrossTitleHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqParacrossTitleHeight.Merge(m, src)
}
func (m *ReqParacrossTitleHeight) XXX_Size() int {
	return xxx_messageInfo_ReqParacrossTitleHeight.Size(m)
}
func (m *ReqParacrossTitleHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqParacrossTitleHeight.DiscardUnknown(m)
}

var xxx_messageInfo_ReqParacrossTitleHeight proto.InternalMessageInfo

func (m *ReqParacrossTitleHeight) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReqParacrossTitleHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RespParacrossTitles struct {
	Titles               []*ReceiptParacrossDone `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RespParacrossTitles) Reset()         { *m = RespParacrossTitles{} }
func (m *RespParacrossTitles) String() string { return proto.CompactTextString(m) }
func (*RespParacrossTitles) ProtoMessage()    {}
func (*RespParacrossTitles) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{16}
}

func (m *RespParacrossTitles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespParacrossTitles.Unmarshal(m, b)
}
func (m *RespParacrossTitles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespParacrossTitles.Marshal(b, m, deterministic)
}
func (m *RespParacrossTitles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespParacrossTitles.Merge(m, src)
}
func (m *RespParacrossTitles) XXX_Size() int {
	return xxx_messageInfo_RespParacrossTitles.Size(m)
}
func (m *RespParacrossTitles) XXX_DiscardUnknown() {
	xxx_messageInfo_RespParacrossTitles.DiscardUnknown(m)
}

var xxx_messageInfo_RespParacrossTitles proto.InternalMessageInfo

func (m *RespParacrossTitles) GetTitles() []*ReceiptParacrossDone {
	if m != nil {
		return m.Titles
	}
	return nil
}

type ReqParacrossTitleHash struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqParacrossTitleHash) Reset()         { *m = ReqParacrossTitleHash{} }
func (m *ReqParacrossTitleHash) String() string { return proto.CompactTextString(m) }
func (*ReqParacrossTitleHash) ProtoMessage()    {}
func (*ReqParacrossTitleHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{17}
}

func (m *ReqParacrossTitleHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqParacrossTitleHash.Unmarshal(m, b)
}
func (m *ReqParacrossTitleHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqParacrossTitleHash.Marshal(b, m, deterministic)
}
func (m *ReqParacrossTitleHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqParacrossTitleHash.Merge(m, src)
}
func (m *ReqParacrossTitleHash) XXX_Size() int {
	return xxx_messageInfo_ReqParacrossTitleHash.Size(m)
}
func (m *ReqParacrossTitleHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqParacrossTitleHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqParacrossTitleHash proto.InternalMessageInfo

func (m *ReqParacrossTitleHash) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReqParacrossTitleHash) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

// 跨链转账相关
type ParacrossAsset struct {
	// input
	From       string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To         string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	IsWithdraw bool   `protobuf:"varint,3,opt,name=isWithdraw,proto3" json:"isWithdraw,omitempty"`
	TxHash     []byte `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Amount     int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Exec       string `protobuf:"bytes,6,opt,name=exec,proto3" json:"exec,omitempty"`
	Symbol     string `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 主链部分
	Height int64 `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	// 平行链部分
	CommitDoneHeight     int64    `protobuf:"varint,21,opt,name=commitDoneHeight,proto3" json:"commitDoneHeight,omitempty"`
	ParaHeight           int64    `protobuf:"varint,22,opt,name=paraHeight,proto3" json:"paraHeight,omitempty"`
	Success              bool     `protobuf:"varint,23,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParacrossAsset) Reset()         { *m = ParacrossAsset{} }
func (m *ParacrossAsset) String() string { return proto.CompactTextString(m) }
func (*ParacrossAsset) ProtoMessage()    {}
func (*ParacrossAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a397e38c9ea6747, []int{18}
}

func (m *ParacrossAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParacrossAsset.Unmarshal(m, b)
}
func (m *ParacrossAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParacrossAsset.Marshal(b, m, deterministic)
}
func (m *ParacrossAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParacrossAsset.Merge(m, src)
}
func (m *ParacrossAsset) XXX_Size() int {
	return xxx_messageInfo_ParacrossAsset.Size(m)
}
func (m *ParacrossAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_ParacrossAsset.DiscardUnknown(m)
}

var xxx_messageInfo_ParacrossAsset proto.InternalMessageInfo

func (m *ParacrossAsset) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ParacrossAsset) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ParacrossAsset) GetIsWithdraw() bool {
	if m != nil {
		return m.IsWithdraw
	}
	return false
}

func (m *ParacrossAsset) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *ParacrossAsset) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ParacrossAsset) GetExec() string {
	if m != nil {
		return m.Exec
	}
	return ""
}

func (m *ParacrossAsset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ParacrossAsset) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossAsset) GetCommitDoneHeight() int64 {
	if m != nil {
		return m.CommitDoneHeight
	}
	return 0
}

func (m *ParacrossAsset) GetParaHeight() int64 {
	if m != nil {
		return m.ParaHeight
	}
	return 0
}

func (m *ParacrossAsset) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ParacrossStatusDetails)(nil), "types.ParacrossStatusDetails")
	proto.RegisterType((*ParacrossHeightStatus)(nil), "types.ParacrossHeightStatus")
	proto.RegisterType((*ParacrossStatus)(nil), "types.ParacrossStatus")
	proto.RegisterType((*ParacrossConsensusStatus)(nil), "types.ParacrossConsensusStatus")
	proto.RegisterType((*ParaBlock2MainMap)(nil), "types.ParaBlock2MainMap")
	proto.RegisterType((*ParaBlock2MainInfo)(nil), "types.ParaBlock2MainInfo")
	proto.RegisterType((*ParacrossNodeStatus)(nil), "types.ParacrossNodeStatus")
	proto.RegisterType((*ParacrossCommitAction)(nil), "types.ParacrossCommitAction")
	proto.RegisterType((*ParacrossMinerAction)(nil), "types.ParacrossMinerAction")
	proto.RegisterType((*ParacrossAction)(nil), "types.ParacrossAction")
	proto.RegisterType((*ReceiptParacrossCommit)(nil), "types.ReceiptParacrossCommit")
	proto.RegisterType((*ReceiptParacrossMiner)(nil), "types.ReceiptParacrossMiner")
	proto.RegisterType((*ReceiptParacrossDone)(nil), "types.ReceiptParacrossDone")
	proto.RegisterType((*ReceiptParacrossRecord)(nil), "types.ReceiptParacrossRecord")
	proto.RegisterType((*ParacrossTx)(nil), "types.ParacrossTx")
	proto.RegisterType((*ReqParacrossTitleHeight)(nil), "types.ReqParacrossTitleHeight")
	proto.RegisterType((*RespParacrossTitles)(nil), "types.RespParacrossTitles")
	proto.RegisterType((*ReqParacrossTitleHash)(nil), "types.ReqParacrossTitleHash")
	proto.RegisterType((*ParacrossAsset)(nil), "types.ParacrossAsset")
}

func init() { proto.RegisterFile("paracross.proto", fileDescriptor_6a397e38c9ea6747) }

var fileDescriptor_6a397e38c9ea6747 = []byte{
	// 1149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xae, 0x7f, 0x73, 0x1c, 0xbb, 0xc9, 0x34, 0x49, 0x57, 0xa6, 0x80, 0xb5, 0x2a, 0xc8,
	0x42, 0x28, 0x42, 0x8e, 0x54, 0x84, 0x10, 0x42, 0x6d, 0x52, 0xc5, 0x29, 0x4d, 0x41, 0x93, 0x20,
	0xae, 0x90, 0xd8, 0xac, 0x27, 0xf1, 0x0a, 0xef, 0xae, 0xbb, 0x33, 0x6e, 0x93, 0x7b, 0x78, 0x05,
	0x9e, 0x80, 0x6b, 0x6e, 0x78, 0x04, 0x24, 0x2e, 0x78, 0x2a, 0x34, 0x67, 0x66, 0x67, 0x77, 0xd6,
	0xc6, 0xaa, 0x80, 0x3b, 0x9f, 0x6f, 0xcf, 0xff, 0xf9, 0xe6, 0xcc, 0x18, 0xee, 0x2d, 0x82, 0x2c,
	0x08, 0xb3, 0x94, 0xf3, 0xc3, 0x45, 0x96, 0x8a, 0x94, 0x34, 0xc5, 0xdd, 0x82, 0xf1, 0xc1, 0xae,
	0xc8, 0x82, 0x84, 0x07, 0xa1, 0x88, 0xd2, 0x44, 0x7d, 0x19, 0x6c, 0x87, 0x69, 0x1c, 0x1b, 0x69,
	0xe7, 0x6a, 0x9e, 0x86, 0x3f, 0x86, 0xb3, 0x20, 0xd2, 0x88, 0xff, 0x02, 0x0e, 0xbe, 0xc9, 0x9d,
	0x5d, 0x88, 0x40, 0x2c, 0xf9, 0x09, 0x13, 0x41, 0x34, 0xe7, 0x64, 0x0f, 0x9a, 0xc1, 0x74, 0x9a,
	0x71, 0xcf, 0x19, 0xd6, 0x47, 0x5b, 0x54, 0x09, 0xe4, 0x21, 0x6c, 0xa1, 0x8f, 0x49, 0xc0, 0x67,
	0x9e, 0x3b, 0xac, 0x8f, 0xb6, 0x69, 0x01, 0xf8, 0xbf, 0x38, 0xb0, 0x6f, 0xdc, 0x4d, 0x58, 0x74,
	0x33, 0x13, 0xca, 0x29, 0x39, 0x80, 0x16, 0xc7, 0x5f, 0x9e, 0x33, 0x74, 0x46, 0x4d, 0xaa, 0x25,
	0x19, 0x45, 0x44, 0x62, 0xce, 0x3c, 0x77, 0xe8, 0xc8, 0x28, 0x28, 0x48, 0xed, 0x19, 0x5a, 0x7b,
	0xf5, 0xa1, 0x33, 0xaa, 0x53, 0x2d, 0x91, 0x4f, 0xa1, 0x3d, 0x55, 0xe9, 0x79, 0x8d, 0xa1, 0x33,
	0xea, 0x8e, 0xdf, 0x3d, 0xc4, 0xca, 0x0f, 0xd7, 0xd7, 0x40, 0x73, 0x6d, 0xff, 0x7b, 0xb8, 0x57,
	0x51, 0x29, 0x22, 0x3b, 0xeb, 0x23, 0xbb, 0x56, 0x64, 0xab, 0x6e, 0x99, 0x94, 0x55, 0xf7, 0xaf,
	0x0e, 0x78, 0xc6, 0xff, 0x71, 0x9a, 0x70, 0x96, 0xf0, 0xe5, 0xe6, 0x40, 0x43, 0xe8, 0xe2, 0x1c,
	0x26, 0xe5, 0x68, 0x65, 0x88, 0x3c, 0x82, 0x5e, 0xa8, 0x5c, 0x4d, 0xca, 0xbd, 0xb0, 0x41, 0xf2,
	0x11, 0xec, 0x68, 0xe0, 0xa9, 0xc9, 0xaf, 0x81, 0x81, 0x56, 0x70, 0xff, 0x67, 0x07, 0x76, 0x65,
	0x9a, 0x88, 0x8c, 0xcf, 0x83, 0x28, 0x39, 0x0f, 0x16, 0xa5, 0x92, 0x9d, 0x7f, 0x2e, 0x59, 0x8d,
	0xa7, 0x00, 0xc8, 0x7b, 0x00, 0x71, 0x91, 0xbe, 0x4a, 0xad, 0x84, 0x90, 0x01, 0x74, 0x50, 0x2a,
	0xf2, 0x31, 0xb2, 0x7f, 0x02, 0xc4, 0x4e, 0xe3, 0x2c, 0xb9, 0x4e, 0xc9, 0x21, 0x34, 0x23, 0xc1,
	0x62, 0x45, 0xb8, 0xee, 0xd8, 0x2b, 0x8d, 0xd6, 0x4a, 0x98, 0x2a, 0x35, 0xff, 0xf7, 0x3a, 0xdc,
	0x37, 0x4d, 0x7f, 0x99, 0x4e, 0x99, 0xee, 0xf7, 0x23, 0xe8, 0xc9, 0x48, 0x45, 0x3b, 0x1c, 0x1c,
	0x97, 0x0d, 0x92, 0x11, 0xdc, 0x2b, 0x80, 0xf2, 0x0c, 0xaa, 0x70, 0x31, 0xbf, 0xfa, 0x7a, 0xa2,
	0x34, 0xac, 0xae, 0xf9, 0xb0, 0xbd, 0xc8, 0x58, 0x11, 0xbc, 0x89, 0xc1, 0x2d, 0xcc, 0xee, 0x6c,
	0xab, 0x42, 0x26, 0xed, 0x41, 0x16, 0xc3, 0x50, 0xa1, 0x6d, 0x3c, 0x18, 0x4c, 0x7a, 0xe0, 0x46,
	0xa1, 0xa3, 0x3c, 0x18, 0x40, 0xf6, 0x5e, 0xdc, 0x1e, 0xa7, 0xcb, 0x44, 0x70, 0x6f, 0x6b, 0xe8,
	0x8c, 0x7a, 0xd4, 0xc8, 0xea, 0x1b, 0x65, 0x7c, 0x39, 0x17, 0x1e, 0xa0, 0xa1, 0x91, 0x89, 0x07,
	0x6d, 0x71, 0x2b, 0x3d, 0x70, 0xaf, 0x8b, 0x47, 0x3b, 0x17, 0x91, 0x8b, 0xb2, 0xcd, 0x97, 0xb9,
	0xe9, 0xb6, 0xea, 0xa9, 0x05, 0xca, 0xcc, 0x35, 0xa0, 0x9c, 0xf4, 0xd0, 0x89, 0x85, 0xf9, 0x5f,
	0x95, 0x36, 0xc4, 0x71, 0x1a, 0xc7, 0x91, 0x78, 0x82, 0xfb, 0x8a, 0x8c, 0xad, 0x0d, 0xd1, 0x1d,
	0x0f, 0xaa, 0x47, 0xbb, 0x18, 0x71, 0xbe, 0x3d, 0xfc, 0xe7, 0xb0, 0x67, 0x3e, 0x9f, 0x47, 0x09,
	0xcb, 0xfe, 0x83, 0xaf, 0x3f, 0xeb, 0xa5, 0x1d, 0xa1, 0xfd, 0x3c, 0x86, 0x56, 0x88, 0x39, 0x6a,
	0x3f, 0x0f, 0xab, 0x7e, 0xca, 0x15, 0x4c, 0x6a, 0x54, 0x6b, 0x93, 0x23, 0x68, 0xc6, 0x32, 0x1d,
	0xa4, 0x4c, 0x77, 0xfc, 0x4e, 0xd5, 0xac, 0x94, 0xeb, 0xa4, 0x46, 0x95, 0x2e, 0xf9, 0x02, 0x7a,
	0x01, 0xe7, 0x4c, 0x5c, 0xca, 0x25, 0x7e, 0xcd, 0x32, 0xbd, 0xe2, 0xf6, 0xb5, 0xf1, 0x13, 0xf9,
	0x8d, 0xe7, 0x1f, 0x27, 0x35, 0x6a, 0x6b, 0x1b, 0xf3, 0xef, 0x22, 0x31, 0x9b, 0x66, 0xc1, 0x1b,
	0x64, 0x5e, 0xd5, 0x3c, 0xff, 0x68, 0xcc, 0x73, 0x80, 0x1c, 0x41, 0x47, 0xe4, 0x81, 0x5b, 0x9b,
	0x03, 0x1b, 0x45, 0x69, 0xf4, 0x26, 0x0f, 0xd7, 0xde, 0x1c, 0xce, 0x28, 0x92, 0x67, 0xd0, 0xcf,
	0x1d, 0x5c, 0xa6, 0xcf, 0x6e, 0x59, 0x88, 0x04, 0x2e, 0xba, 0x64, 0xc7, 0x53, 0x2a, 0x93, 0x1a,
	0xad, 0x18, 0x91, 0x3e, 0xb8, 0xe2, 0x0e, 0xcf, 0x6c, 0x93, 0xba, 0xe2, 0xee, 0x69, 0x1b, 0x9a,
	0xaf, 0x83, 0xf9, 0x92, 0xf9, 0x7f, 0x39, 0x70, 0x40, 0x59, 0xc8, 0xa2, 0x85, 0xa8, 0xcc, 0x89,
	0x10, 0x68, 0xc8, 0x6b, 0x4c, 0x6f, 0x62, 0xfc, 0x5d, 0xe2, 0x8a, 0xfb, 0xb6, 0x5c, 0x21, 0x9f,
	0x40, 0x63, 0x91, 0xb1, 0xd7, 0x7a, 0xbc, 0x2b, 0xac, 0x28, 0xdf, 0x7c, 0x14, 0x35, 0xc9, 0x63,
	0x68, 0x87, 0xcb, 0x2c, 0x63, 0x89, 0xd0, 0x63, 0xdd, 0x6c, 0x94, 0x2b, 0xcb, 0xe3, 0x52, 0xad,
	0x05, 0xc9, 0xf3, 0xaf, 0x28, 0xfe, 0x93, 0x0b, 0x7b, 0x55, 0x6f, 0x27, 0x69, 0xc2, 0xe4, 0x32,
	0x17, 0xa9, 0x08, 0xe6, 0xd2, 0x26, 0xbf, 0xa1, 0x4b, 0x88, 0xbc, 0xac, 0x50, 0x52, 0x6d, 0xd4,
	0x4d, 0x2f, 0x43, 0xe4, 0x43, 0xe8, 0xc7, 0x29, 0x17, 0x17, 0x41, 0xcc, 0xb4, 0x52, 0x1d, 0x95,
	0x2a, 0x68, 0xb1, 0x4c, 0x1b, 0xeb, 0x97, 0x69, 0xb3, 0x7a, 0x05, 0x15, 0x6b, 0xae, 0xb5, 0x69,
	0xcd, 0xb5, 0x37, 0xac, 0xb9, 0x8e, 0xbd, 0xe6, 0xfc, 0x1f, 0x56, 0xf9, 0x41, 0x59, 0x98, 0x66,
	0xd3, 0xff, 0x8b, 0x1f, 0xfe, 0x07, 0xd0, 0x35, 0x9f, 0x2f, 0x6f, 0x65, 0x79, 0x6a, 0x91, 0x6a,
	0xc7, 0x5a, 0xf2, 0x4f, 0xe1, 0x01, 0x65, 0xaf, 0x0a, 0x4d, 0xd9, 0x8b, 0xea, 0xa5, 0xf3, 0x36,
	0xaf, 0x13, 0xff, 0x39, 0xdc, 0xa7, 0x8c, 0x2f, 0x6c, 0x4f, 0x9c, 0x1c, 0x41, 0x0b, 0xed, 0xf2,
	0x2b, 0x35, 0x3f, 0x61, 0xeb, 0x38, 0x40, 0xb5, 0xaa, 0x62, 0x5c, 0x35, 0x29, 0xd9, 0xee, 0xf5,
	0x29, 0xad, 0xbc, 0x12, 0xac, 0x87, 0xd1, 0x6f, 0x2e, 0xf4, 0x8b, 0xa5, 0x2a, 0x0f, 0xb6, 0xec,
	0xf1, 0x75, 0x96, 0xc6, 0x79, 0x8f, 0xe5, 0x6f, 0x3c, 0xcb, 0xa9, 0x7e, 0x63, 0xb8, 0x22, 0x95,
	0x7c, 0x8c, 0xcc, 0xf2, 0x40, 0x26, 0x75, 0x68, 0x09, 0x29, 0x35, 0xb4, 0x81, 0x11, 0xb5, 0x24,
	0xf1, 0x20, 0x96, 0x04, 0xc8, 0x79, 0xa4, 0x24, 0x19, 0x93, 0xc9, 0x45, 0xd3, 0x52, 0x31, 0xe5,
	0x6f, 0x7c, 0x91, 0xde, 0xc5, 0x57, 0xe9, 0x1c, 0xb9, 0xb3, 0x45, 0xb5, 0x54, 0xea, 0x31, 0x58,
	0x5c, 0xc4, 0x87, 0x96, 0xe4, 0xb0, 0xec, 0x96, 0x7e, 0x31, 0xec, 0xa3, 0xc6, 0x0a, 0x2e, 0xf3,
	0x97, 0x4f, 0x74, 0xad, 0x75, 0xa0, 0x1e, 0x47, 0x05, 0x22, 0x2f, 0x5a, 0xbe, 0x0c, 0x43, 0xc6,
	0xb9, 0xf7, 0x00, 0x8b, 0xcb, 0xc5, 0xf1, 0x1f, 0x2e, 0x6c, 0x99, 0xd7, 0x3d, 0xf9, 0x12, 0x3a,
	0xa7, 0x4c, 0xe0, 0x08, 0xc8, 0x8e, 0x19, 0xde, 0xab, 0x0b, 0x91, 0x45, 0xc9, 0xcd, 0xe0, 0xfd,
	0xd5, 0xdb, 0xc8, 0x7a, 0x79, 0xfa, 0x35, 0xf2, 0x19, 0xc0, 0x8b, 0x88, 0x0b, 0xcd, 0x87, 0x5e,
	0xe1, 0xe2, 0x65, 0x34, 0x1f, 0x0c, 0x8c, 0xb8, 0x42, 0x1d, 0xbf, 0x46, 0xbe, 0x86, 0x7e, 0x1e,
	0x3b, 0xaf, 0xaa, 0x30, 0x5f, 0xc7, 0xd9, 0xc1, 0x26, 0x7a, 0xf9, 0x35, 0xf2, 0x39, 0xec, 0x9c,
	0x32, 0x81, 0x24, 0x30, 0x2f, 0x86, 0x7e, 0xe1, 0x52, 0x0e, 0x70, 0xb0, 0x5f, 0x2d, 0x09, 0xd5,
	0xfd, 0x1a, 0xf9, 0x18, 0x5a, 0x67, 0xfc, 0xe2, 0x2e, 0x09, 0xab, 0x45, 0xec, 0x6a, 0xf1, 0x8c,
	0x1f, 0x07, 0xcb, 0x9b, 0x99, 0xf8, 0x76, 0xe1, 0xd7, 0xae, 0x5a, 0xf8, 0xe7, 0xe6, 0xe8, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x60, 0x33, 0x41, 0x29, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ParacrossClient is the client API for Paracross service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParacrossClient interface {
	GetTitle(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*ParacrossConsensusStatus, error)
	ListTitles(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*RespParacrossTitles, error)
	GetTitleHeight(ctx context.Context, in *ReqParacrossTitleHeight, opts ...grpc.CallOption) (*ReceiptParacrossDone, error)
	GetAssetTxResult(ctx context.Context, in *types.ReqHash, opts ...grpc.CallOption) (*ParacrossAsset, error)
	IsSync(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*types.IsCaughtUp, error)
}

type paracrossClient struct {
	cc *grpc.ClientConn
}

func NewParacrossClient(cc *grpc.ClientConn) ParacrossClient {
	return &paracrossClient{cc}
}

func (c *paracrossClient) GetTitle(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*ParacrossConsensusStatus, error) {
	out := new(ParacrossConsensusStatus)
	err := c.cc.Invoke(ctx, "/types.paracross/GetTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paracrossClient) ListTitles(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*RespParacrossTitles, error) {
	out := new(RespParacrossTitles)
	err := c.cc.Invoke(ctx, "/types.paracross/ListTitles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paracrossClient) GetTitleHeight(ctx context.Context, in *ReqParacrossTitleHeight, opts ...grpc.CallOption) (*ReceiptParacrossDone, error) {
	out := new(ReceiptParacrossDone)
	err := c.cc.Invoke(ctx, "/types.paracross/GetTitleHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paracrossClient) GetAssetTxResult(ctx context.Context, in *types.ReqHash, opts ...grpc.CallOption) (*ParacrossAsset, error) {
	out := new(ParacrossAsset)
	err := c.cc.Invoke(ctx, "/types.paracross/GetAssetTxResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paracrossClient) IsSync(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*types.IsCaughtUp, error) {
	out := new(types.IsCaughtUp)
	err := c.cc.Invoke(ctx, "/types.paracross/IsSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParacrossServer is the server API for Paracross service.
type ParacrossServer interface {
	GetTitle(context.Context, *types.ReqString) (*ParacrossConsensusStatus, error)
	ListTitles(context.Context, *types.ReqNil) (*RespParacrossTitles, error)
	GetTitleHeight(context.Context, *ReqParacrossTitleHeight) (*ReceiptParacrossDone, error)
	GetAssetTxResult(context.Context, *types.ReqHash) (*ParacrossAsset, error)
	IsSync(context.Context, *types.ReqNil) (*types.IsCaughtUp, error)
}

func RegisterParacrossServer(s *grpc.Server, srv ParacrossServer) {
	s.RegisterService(&_Paracross_serviceDesc, srv)
}

func _Paracross_GetTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParacrossServer).GetTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.paracross/GetTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParacrossServer).GetTitle(ctx, req.(*types.ReqString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paracross_ListTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParacrossServer).ListTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.paracross/ListTitles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParacrossServer).ListTitles(ctx, req.(*types.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paracross_GetTitleHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqParacrossTitleHeight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParacrossServer).GetTitleHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.paracross/GetTitleHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParacrossServer).GetTitleHeight(ctx, req.(*ReqParacrossTitleHeight))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paracross_GetAssetTxResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParacrossServer).GetAssetTxResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.paracross/GetAssetTxResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParacrossServer).GetAssetTxResult(ctx, req.(*types.ReqHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paracross_IsSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParacrossServer).IsSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.paracross/IsSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParacrossServer).IsSync(ctx, req.(*types.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

var _Paracross_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.paracross",
	HandlerType: (*ParacrossServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTitle",
			Handler:    _Paracross_GetTitle_Handler,
		},
		{
			MethodName: "ListTitles",
			Handler:    _Paracross_ListTitles_Handler,
		},
		{
			MethodName: "GetTitleHeight",
			Handler:    _Paracross_GetTitleHeight_Handler,
		},
		{
			MethodName: "GetAssetTxResult",
			Handler:    _Paracross_GetAssetTxResult_Handler,
		},
		{
			MethodName: "IsSync",
			Handler:    _Paracross_IsSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paracross.proto",
}
