// Code generated by protoc-gen-go. DO NOT EDIT.
// source: f3d.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoundInfo struct {
	// 游戏轮次
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本轮游戏开始事件
	BeginTime int64 `protobuf:"varint,2,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	// 本轮游戏结束时间
	EndTime int64 `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	// 本轮游戏目前为止最后一把钥匙持有人（游戏开奖时，这个就是中奖人）
	LastOwner string `protobuf:"bytes,4,opt,name=lastOwner,proto3" json:"lastOwner,omitempty"`
	// 最后一把钥匙的购买时间
	LastKeyTime int64 `protobuf:"varint,5,opt,name=lastKeyTime,proto3" json:"lastKeyTime,omitempty"`
	// 最后一把钥匙的价格
	LastKeyPrice float32 `protobuf:"fixed32,6,opt,name=lastKeyPrice,proto3" json:"lastKeyPrice,omitempty"`
	// 本轮游戏奖金池总额
	BonusPool float32 `protobuf:"fixed32,7,opt,name=bonusPool,proto3" json:"bonusPool,omitempty"`
	// 本轮游戏参与地址数
	UserCount int64 `protobuf:"varint,8,opt,name=userCount,proto3" json:"userCount,omitempty"`
	// 本轮游戏募集到的key个数
	KeyCount int64 `protobuf:"varint,9,opt,name=keyCount,proto3" json:"keyCount,omitempty"`
	// 距离开奖剩余时间
	RemainTime           int64    `protobuf:"varint,10,opt,name=remainTime,proto3" json:"remainTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundInfo) Reset()         { *m = RoundInfo{} }
func (m *RoundInfo) String() string { return proto.CompactTextString(m) }
func (*RoundInfo) ProtoMessage()    {}
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{0}
}
func (m *RoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfo.Unmarshal(m, b)
}
func (m *RoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfo.Marshal(b, m, deterministic)
}
func (dst *RoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfo.Merge(dst, src)
}
func (m *RoundInfo) XXX_Size() int {
	return xxx_messageInfo_RoundInfo.Size(m)
}
func (m *RoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfo proto.InternalMessageInfo

func (m *RoundInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *RoundInfo) GetBeginTime() int64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *RoundInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoundInfo) GetLastOwner() string {
	if m != nil {
		return m.LastOwner
	}
	return ""
}

func (m *RoundInfo) GetLastKeyTime() int64 {
	if m != nil {
		return m.LastKeyTime
	}
	return 0
}

func (m *RoundInfo) GetLastKeyPrice() float32 {
	if m != nil {
		return m.LastKeyPrice
	}
	return 0
}

func (m *RoundInfo) GetBonusPool() float32 {
	if m != nil {
		return m.BonusPool
	}
	return 0
}

func (m *RoundInfo) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *RoundInfo) GetKeyCount() int64 {
	if m != nil {
		return m.KeyCount
	}
	return 0
}

func (m *RoundInfo) GetRemainTime() int64 {
	if m != nil {
		return m.RemainTime
	}
	return 0
}

type KeyInfo struct {
	// 游戏轮次  (是由系统合约填写后存储）
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本次购买key的价格 (是由系统合约填写后存储）
	KeyPrice float32 `protobuf:"fixed32,2,opt,name=keyPrice,proto3" json:"keyPrice,omitempty"`
	// 用户本次买的key的数量
	KeyNum int64 `protobuf:"varint,3,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	// 用户地址 (是由系统合约填写后存储）
	Addr string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// 交易确认存储时间（被打包的时间）
	BuyKeyTime int64 `protobuf:"varint,7,opt,name=buyKeyTime,proto3" json:"buyKeyTime,omitempty"`
	// 买票的txHash
	BuyKeyTxHash         string   `protobuf:"bytes,9,opt,name=buyKeyTxHash,proto3" json:"buyKeyTxHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyInfo) Reset()         { *m = KeyInfo{} }
func (m *KeyInfo) String() string { return proto.CompactTextString(m) }
func (*KeyInfo) ProtoMessage()    {}
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{1}
}
func (m *KeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyInfo.Unmarshal(m, b)
}
func (m *KeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyInfo.Marshal(b, m, deterministic)
}
func (dst *KeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyInfo.Merge(dst, src)
}
func (m *KeyInfo) XXX_Size() int {
	return xxx_messageInfo_KeyInfo.Size(m)
}
func (m *KeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KeyInfo proto.InternalMessageInfo

func (m *KeyInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *KeyInfo) GetKeyPrice() float32 {
	if m != nil {
		return m.KeyPrice
	}
	return 0
}

func (m *KeyInfo) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

func (m *KeyInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *KeyInfo) GetBuyKeyTime() int64 {
	if m != nil {
		return m.BuyKeyTime
	}
	return 0
}

func (m *KeyInfo) GetBuyKeyTxHash() string {
	if m != nil {
		return m.BuyKeyTxHash
	}
	return ""
}

// message for execs.f3d
type F3DAction struct {
	// Types that are valid to be assigned to Value:
	//	*F3DAction_Start
	//	*F3DAction_Draw
	//	*F3DAction_Buy
	Value                isF3DAction_Value `protobuf_oneof:"value"`
	Ty                   int32             `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *F3DAction) Reset()         { *m = F3DAction{} }
func (m *F3DAction) String() string { return proto.CompactTextString(m) }
func (*F3DAction) ProtoMessage()    {}
func (*F3DAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{2}
}
func (m *F3DAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DAction.Unmarshal(m, b)
}
func (m *F3DAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DAction.Marshal(b, m, deterministic)
}
func (dst *F3DAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DAction.Merge(dst, src)
}
func (m *F3DAction) XXX_Size() int {
	return xxx_messageInfo_F3DAction.Size(m)
}
func (m *F3DAction) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DAction.DiscardUnknown(m)
}

var xxx_messageInfo_F3DAction proto.InternalMessageInfo

type isF3DAction_Value interface {
	isF3DAction_Value()
}

type F3DAction_Start struct {
	Start *F3DStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}
type F3DAction_Draw struct {
	Draw *F3DLuckyDraw `protobuf:"bytes,2,opt,name=draw,proto3,oneof"`
}
type F3DAction_Buy struct {
	Buy *F3DBuyKey `protobuf:"bytes,3,opt,name=buy,proto3,oneof"`
}

func (*F3DAction_Start) isF3DAction_Value() {}
func (*F3DAction_Draw) isF3DAction_Value()  {}
func (*F3DAction_Buy) isF3DAction_Value()   {}

func (m *F3DAction) GetValue() isF3DAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *F3DAction) GetStart() *F3DStart {
	if x, ok := m.GetValue().(*F3DAction_Start); ok {
		return x.Start
	}
	return nil
}

func (m *F3DAction) GetDraw() *F3DLuckyDraw {
	if x, ok := m.GetValue().(*F3DAction_Draw); ok {
		return x.Draw
	}
	return nil
}

func (m *F3DAction) GetBuy() *F3DBuyKey {
	if x, ok := m.GetValue().(*F3DAction_Buy); ok {
		return x.Buy
	}
	return nil
}

func (m *F3DAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*F3DAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _F3DAction_OneofMarshaler, _F3DAction_OneofUnmarshaler, _F3DAction_OneofSizer, []interface{}{
		(*F3DAction_Start)(nil),
		(*F3DAction_Draw)(nil),
		(*F3DAction_Buy)(nil),
	}
}

func _F3DAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*F3DAction)
	// value
	switch x := m.Value.(type) {
	case *F3DAction_Start:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Start); err != nil {
			return err
		}
	case *F3DAction_Draw:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Draw); err != nil {
			return err
		}
	case *F3DAction_Buy:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Buy); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("F3DAction.Value has unexpected type %T", x)
	}
	return nil
}

func _F3DAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*F3DAction)
	switch tag {
	case 1: // value.start
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DStart)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Start{msg}
		return true, err
	case 2: // value.draw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DLuckyDraw)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Draw{msg}
		return true, err
	case 3: // value.buy
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DBuyKey)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Buy{msg}
		return true, err
	default:
		return false, nil
	}
}

func _F3DAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*F3DAction)
	// value
	switch x := m.Value.(type) {
	case *F3DAction_Start:
		s := proto.Size(x.Start)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *F3DAction_Draw:
		s := proto.Size(x.Draw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *F3DAction_Buy:
		s := proto.Size(x.Buy)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type F3DStart struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DStart) Reset()         { *m = F3DStart{} }
func (m *F3DStart) String() string { return proto.CompactTextString(m) }
func (*F3DStart) ProtoMessage()    {}
func (*F3DStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{3}
}
func (m *F3DStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DStart.Unmarshal(m, b)
}
func (m *F3DStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DStart.Marshal(b, m, deterministic)
}
func (dst *F3DStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DStart.Merge(dst, src)
}
func (m *F3DStart) XXX_Size() int {
	return xxx_messageInfo_F3DStart.Size(m)
}
func (m *F3DStart) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DStart.DiscardUnknown(m)
}

var xxx_messageInfo_F3DStart proto.InternalMessageInfo

func (m *F3DStart) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DLuckyDraw struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DLuckyDraw) Reset()         { *m = F3DLuckyDraw{} }
func (m *F3DLuckyDraw) String() string { return proto.CompactTextString(m) }
func (*F3DLuckyDraw) ProtoMessage()    {}
func (*F3DLuckyDraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{4}
}
func (m *F3DLuckyDraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DLuckyDraw.Unmarshal(m, b)
}
func (m *F3DLuckyDraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DLuckyDraw.Marshal(b, m, deterministic)
}
func (dst *F3DLuckyDraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DLuckyDraw.Merge(dst, src)
}
func (m *F3DLuckyDraw) XXX_Size() int {
	return xxx_messageInfo_F3DLuckyDraw.Size(m)
}
func (m *F3DLuckyDraw) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DLuckyDraw.DiscardUnknown(m)
}

var xxx_messageInfo_F3DLuckyDraw proto.InternalMessageInfo

func (m *F3DLuckyDraw) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DBuyKey struct {
	// 用户本次买的key的数量
	KeyNum               int64    `protobuf:"varint,3,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DBuyKey) Reset()         { *m = F3DBuyKey{} }
func (m *F3DBuyKey) String() string { return proto.CompactTextString(m) }
func (*F3DBuyKey) ProtoMessage()    {}
func (*F3DBuyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{5}
}
func (m *F3DBuyKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DBuyKey.Unmarshal(m, b)
}
func (m *F3DBuyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DBuyKey.Marshal(b, m, deterministic)
}
func (dst *F3DBuyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DBuyKey.Merge(dst, src)
}
func (m *F3DBuyKey) XXX_Size() int {
	return xxx_messageInfo_F3DBuyKey.Size(m)
}
func (m *F3DBuyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DBuyKey.DiscardUnknown(m)
}

var xxx_messageInfo_F3DBuyKey proto.InternalMessageInfo

func (m *F3DBuyKey) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

// 查询f3d 游戏信息,这里面其实包含了key的最新价格信息
type QueryF3DByRound struct {
	// 轮次，默认查询最新的
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryF3DByRound) Reset()         { *m = QueryF3DByRound{} }
func (m *QueryF3DByRound) String() string { return proto.CompactTextString(m) }
func (*QueryF3DByRound) ProtoMessage()    {}
func (*QueryF3DByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{6}
}
func (m *QueryF3DByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryF3DByRound.Unmarshal(m, b)
}
func (m *QueryF3DByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryF3DByRound.Marshal(b, m, deterministic)
}
func (dst *QueryF3DByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryF3DByRound.Merge(dst, src)
}
func (m *QueryF3DByRound) XXX_Size() int {
	return xxx_messageInfo_QueryF3DByRound.Size(m)
}
func (m *QueryF3DByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryF3DByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryF3DByRound proto.InternalMessageInfo

func (m *QueryF3DByRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type QueryF3DListByRound struct {
	// 轮次，默认查询最新的
	StartRound int64 `protobuf:"varint,1,opt,name=startRound,proto3" json:"startRound,omitempty"`
	// 单页返回多少条记录，默认返回10条，单次最多返回50条
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryF3DListByRound) Reset()         { *m = QueryF3DListByRound{} }
func (m *QueryF3DListByRound) String() string { return proto.CompactTextString(m) }
func (*QueryF3DListByRound) ProtoMessage()    {}
func (*QueryF3DListByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{7}
}
func (m *QueryF3DListByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryF3DListByRound.Unmarshal(m, b)
}
func (m *QueryF3DListByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryF3DListByRound.Marshal(b, m, deterministic)
}
func (dst *QueryF3DListByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryF3DListByRound.Merge(dst, src)
}
func (m *QueryF3DListByRound) XXX_Size() int {
	return xxx_messageInfo_QueryF3DListByRound.Size(m)
}
func (m *QueryF3DListByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryF3DListByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryF3DListByRound proto.InternalMessageInfo

func (m *QueryF3DListByRound) GetStartRound() int64 {
	if m != nil {
		return m.StartRound
	}
	return 0
}

func (m *QueryF3DListByRound) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryF3DListByRound) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// key 信息查询
type QueryKeysByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryKeysByRoundAndAddr) Reset()         { *m = QueryKeysByRoundAndAddr{} }
func (m *QueryKeysByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryKeysByRoundAndAddr) ProtoMessage()    {}
func (*QueryKeysByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{8}
}
func (m *QueryKeysByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryKeysByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryKeysByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryKeysByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryKeysByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKeysByRoundAndAddr.Merge(dst, src)
}
func (m *QueryKeysByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryKeysByRoundAndAddr.Size(m)
}
func (m *QueryKeysByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKeysByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKeysByRoundAndAddr proto.InternalMessageInfo

func (m *QueryKeysByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryKeysByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 用户key数量查询
type QueryKeyCountByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryKeyCountByRoundAndAddr) Reset()         { *m = QueryKeyCountByRoundAndAddr{} }
func (m *QueryKeyCountByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryKeyCountByRoundAndAddr) ProtoMessage()    {}
func (*QueryKeyCountByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{9}
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryKeyCountByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKeyCountByRoundAndAddr.Merge(dst, src)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Size(m)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKeyCountByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKeyCountByRoundAndAddr proto.InternalMessageInfo

func (m *QueryKeyCountByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryKeyCountByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type F3DRecord struct {
	// 用户地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// index
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// round
	Round                int64    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DRecord) Reset()         { *m = F3DRecord{} }
func (m *F3DRecord) String() string { return proto.CompactTextString(m) }
func (*F3DRecord) ProtoMessage()    {}
func (*F3DRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{10}
}
func (m *F3DRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DRecord.Unmarshal(m, b)
}
func (m *F3DRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DRecord.Marshal(b, m, deterministic)
}
func (dst *F3DRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DRecord.Merge(dst, src)
}
func (m *F3DRecord) XXX_Size() int {
	return xxx_messageInfo_F3DRecord.Size(m)
}
func (m *F3DRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DRecord.DiscardUnknown(m)
}

var xxx_messageInfo_F3DRecord proto.InternalMessageInfo

func (m *F3DRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *F3DRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *F3DRecord) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// f3d round查询返回数据
type ReplyF3DList struct {
	Rounds               []*RoundInfo `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyF3DList) Reset()         { *m = ReplyF3DList{} }
func (m *ReplyF3DList) String() string { return proto.CompactTextString(m) }
func (*ReplyF3DList) ProtoMessage()    {}
func (*ReplyF3DList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{11}
}
func (m *ReplyF3DList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyF3DList.Unmarshal(m, b)
}
func (m *ReplyF3DList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyF3DList.Marshal(b, m, deterministic)
}
func (dst *ReplyF3DList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyF3DList.Merge(dst, src)
}
func (m *ReplyF3DList) XXX_Size() int {
	return xxx_messageInfo_ReplyF3DList.Size(m)
}
func (m *ReplyF3DList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyF3DList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyF3DList proto.InternalMessageInfo

func (m *ReplyF3DList) GetRounds() []*RoundInfo {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type ReplyF3D struct {
	Round                *RoundInfo `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyF3D) Reset()         { *m = ReplyF3D{} }
func (m *ReplyF3D) String() string { return proto.CompactTextString(m) }
func (*ReplyF3D) ProtoMessage()    {}
func (*ReplyF3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{12}
}
func (m *ReplyF3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyF3D.Unmarshal(m, b)
}
func (m *ReplyF3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyF3D.Marshal(b, m, deterministic)
}
func (dst *ReplyF3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyF3D.Merge(dst, src)
}
func (m *ReplyF3D) XXX_Size() int {
	return xxx_messageInfo_ReplyF3D.Size(m)
}
func (m *ReplyF3D) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyF3D.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyF3D proto.InternalMessageInfo

func (m *ReplyF3D) GetRound() *RoundInfo {
	if m != nil {
		return m.Round
	}
	return nil
}

// 用户查询买的key信息返回数据
type ReplyKeyList struct {
	Keys                 []*KeyInfo `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyKeyList) Reset()         { *m = ReplyKeyList{} }
func (m *ReplyKeyList) String() string { return proto.CompactTextString(m) }
func (*ReplyKeyList) ProtoMessage()    {}
func (*ReplyKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{13}
}
func (m *ReplyKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKeyList.Unmarshal(m, b)
}
func (m *ReplyKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKeyList.Marshal(b, m, deterministic)
}
func (dst *ReplyKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKeyList.Merge(dst, src)
}
func (m *ReplyKeyList) XXX_Size() int {
	return xxx_messageInfo_ReplyKeyList.Size(m)
}
func (m *ReplyKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKeyList proto.InternalMessageInfo

func (m *ReplyKeyList) GetKeys() []*KeyInfo {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ReplyKey struct {
	Key                  *KeyInfo `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyKey) Reset()         { *m = ReplyKey{} }
func (m *ReplyKey) String() string { return proto.CompactTextString(m) }
func (*ReplyKey) ProtoMessage()    {}
func (*ReplyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{14}
}
func (m *ReplyKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKey.Unmarshal(m, b)
}
func (m *ReplyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKey.Marshal(b, m, deterministic)
}
func (dst *ReplyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKey.Merge(dst, src)
}
func (m *ReplyKey) XXX_Size() int {
	return xxx_messageInfo_ReplyKey.Size(m)
}
func (m *ReplyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKey proto.InternalMessageInfo

func (m *ReplyKey) GetKey() *KeyInfo {
	if m != nil {
		return m.Key
	}
	return nil
}

type ReplyKeyCount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyKeyCount) Reset()         { *m = ReplyKeyCount{} }
func (m *ReplyKeyCount) String() string { return proto.CompactTextString(m) }
func (*ReplyKeyCount) ProtoMessage()    {}
func (*ReplyKeyCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{15}
}
func (m *ReplyKeyCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKeyCount.Unmarshal(m, b)
}
func (m *ReplyKeyCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKeyCount.Marshal(b, m, deterministic)
}
func (dst *ReplyKeyCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKeyCount.Merge(dst, src)
}
func (m *ReplyKeyCount) XXX_Size() int {
	return xxx_messageInfo_ReplyKeyCount.Size(m)
}
func (m *ReplyKeyCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKeyCount.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKeyCount proto.InternalMessageInfo

func (m *ReplyKeyCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 合约内部日志记录，待补全
type ReceiptF3D struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Round                int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptF3D) Reset()         { *m = ReceiptF3D{} }
func (m *ReceiptF3D) String() string { return proto.CompactTextString(m) }
func (*ReceiptF3D) ProtoMessage()    {}
func (*ReceiptF3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_901bff1346cea110, []int{16}
}
func (m *ReceiptF3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptF3D.Unmarshal(m, b)
}
func (m *ReceiptF3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptF3D.Marshal(b, m, deterministic)
}
func (dst *ReceiptF3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptF3D.Merge(dst, src)
}
func (m *ReceiptF3D) XXX_Size() int {
	return xxx_messageInfo_ReceiptF3D.Size(m)
}
func (m *ReceiptF3D) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptF3D.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptF3D proto.InternalMessageInfo

func (m *ReceiptF3D) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptF3D) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ReceiptF3D) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*RoundInfo)(nil), "types.RoundInfo")
	proto.RegisterType((*KeyInfo)(nil), "types.KeyInfo")
	proto.RegisterType((*F3DAction)(nil), "types.F3dAction")
	proto.RegisterType((*F3DStart)(nil), "types.F3dStart")
	proto.RegisterType((*F3DLuckyDraw)(nil), "types.F3dLuckyDraw")
	proto.RegisterType((*F3DBuyKey)(nil), "types.F3dBuyKey")
	proto.RegisterType((*QueryF3DByRound)(nil), "types.QueryF3dByRound")
	proto.RegisterType((*QueryF3DListByRound)(nil), "types.QueryF3dListByRound")
	proto.RegisterType((*QueryKeysByRoundAndAddr)(nil), "types.QueryKeysByRoundAndAddr")
	proto.RegisterType((*QueryKeyCountByRoundAndAddr)(nil), "types.QueryKeyCountByRoundAndAddr")
	proto.RegisterType((*F3DRecord)(nil), "types.F3dRecord")
	proto.RegisterType((*ReplyF3DList)(nil), "types.ReplyF3dList")
	proto.RegisterType((*ReplyF3D)(nil), "types.ReplyF3d")
	proto.RegisterType((*ReplyKeyList)(nil), "types.ReplyKeyList")
	proto.RegisterType((*ReplyKey)(nil), "types.ReplyKey")
	proto.RegisterType((*ReplyKeyCount)(nil), "types.ReplyKeyCount")
	proto.RegisterType((*ReceiptF3D)(nil), "types.ReceiptF3d")
}

func init() { proto.RegisterFile("f3d.proto", fileDescriptor_f3d_901bff1346cea110) }

var fileDescriptor_f3d_901bff1346cea110 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xed, 0x38, 0x89, 0x27, 0xfd, 0xda, 0x4f, 0xdb, 0x0a, 0x2c, 0x40, 0x95, 0xb5, 0x14,
	0x1a, 0x24, 0xd4, 0x8b, 0xe4, 0x86, 0xdb, 0xb6, 0xa8, 0x04, 0xa5, 0x82, 0xb2, 0xf0, 0x02, 0x4e,
	0x3c, 0x05, 0x2b, 0xa9, 0x1d, 0xf9, 0x87, 0x76, 0x5f, 0x86, 0x17, 0xe0, 0x9a, 0xf7, 0x43, 0x3b,
	0xde, 0xb5, 0xb7, 0xa8, 0xe5, 0x82, 0x3b, 0x9f, 0x39, 0x33, 0x7b, 0x66, 0xce, 0x8e, 0x17, 0x82,
	0xab, 0x69, 0x72, 0xbc, 0x29, 0xf2, 0x2a, 0x67, 0x7e, 0x25, 0x37, 0x58, 0xf2, 0x5f, 0x2e, 0x04,
	0x22, 0xaf, 0xb3, 0xe4, 0x7d, 0x76, 0x95, 0xb3, 0x7d, 0xf0, 0x0b, 0x05, 0x42, 0x27, 0x72, 0xc6,
	0x9e, 0x68, 0x00, 0x7b, 0x06, 0xc1, 0x02, 0xbf, 0xa6, 0xd9, 0x97, 0xf4, 0x1a, 0x43, 0x97, 0x98,
	0x2e, 0xc0, 0x42, 0x18, 0x60, 0x96, 0x10, 0xe7, 0x11, 0x67, 0xa0, 0xaa, 0x5b, 0xc7, 0x65, 0xf5,
	0xf1, 0x26, 0xc3, 0x22, 0xec, 0x45, 0xce, 0x38, 0x10, 0x5d, 0x80, 0x45, 0x30, 0x52, 0x60, 0x8e,
	0x92, 0x6a, 0x7d, 0xaa, 0xb5, 0x43, 0x8c, 0xc3, 0xb6, 0x86, 0x97, 0x45, 0xba, 0xc4, 0xb0, 0x1f,
	0x39, 0x63, 0x57, 0xdc, 0x89, 0x51, 0x6f, 0x79, 0x56, 0x97, 0x97, 0x79, 0xbe, 0x0e, 0x07, 0x94,
	0xd0, 0x05, 0x14, 0x5b, 0x97, 0x58, 0x9c, 0xe5, 0x75, 0x56, 0x85, 0xc3, 0xa6, 0xf3, 0x36, 0xc0,
	0x9e, 0xc0, 0x70, 0x85, 0xb2, 0x21, 0x03, 0x22, 0x5b, 0xcc, 0x0e, 0x00, 0x0a, 0xbc, 0x8e, 0xf5,
	0xd0, 0x40, 0xac, 0x15, 0xe1, 0x3f, 0x1d, 0x18, 0xcc, 0x51, 0xfe, 0xc5, 0xb5, 0xe6, 0xf4, 0xa6,
	0x73, 0x97, 0x1a, 0x6b, 0x31, 0x7b, 0x04, 0xfd, 0x15, 0xca, 0x0f, 0xf5, 0xb5, 0xb6, 0x4c, 0x23,
	0xc6, 0xa0, 0x17, 0x27, 0x89, 0x31, 0x8b, 0xbe, 0x55, 0x27, 0x8b, 0x5a, 0x1a, 0x9b, 0x06, 0x4d,
	0x27, 0x5d, 0x44, 0xb9, 0xa4, 0xd1, 0xed, 0x2c, 0x2e, 0xbf, 0xd1, 0x24, 0x81, 0xb8, 0x13, 0xe3,
	0x3f, 0x1c, 0x08, 0xce, 0xa7, 0xc9, 0xc9, 0xb2, 0x4a, 0xf3, 0x8c, 0x1d, 0x81, 0x5f, 0x56, 0x71,
	0x51, 0x51, 0xbf, 0xa3, 0xc9, 0xee, 0x31, 0xad, 0xc2, 0xf1, 0xf9, 0x34, 0xf9, 0xac, 0xc2, 0xb3,
	0x2d, 0xd1, 0xf0, 0xec, 0x15, 0xf4, 0x92, 0x22, 0xbe, 0xa1, 0xf6, 0x47, 0x93, 0xbd, 0x2e, 0xef,
	0xa2, 0x5e, 0xae, 0xe4, 0xdb, 0x22, 0xbe, 0x99, 0x6d, 0x09, 0x4a, 0x61, 0x87, 0xe0, 0x2d, 0x6a,
	0x49, 0xe3, 0x8c, 0x26, 0xff, 0x77, 0x99, 0xa7, 0xd4, 0xc6, 0x6c, 0x4b, 0x28, 0x9a, 0xed, 0x80,
	0x5b, 0x49, 0x9a, 0xce, 0x17, 0x6e, 0x25, 0x4f, 0x07, 0xe0, 0x7f, 0x8f, 0xd7, 0x35, 0xf2, 0x08,
	0x86, 0x46, 0x5e, 0xd9, 0x29, 0x6c, 0x3b, 0x09, 0xf0, 0x43, 0xd8, 0xb6, 0x85, 0x1f, 0xc8, 0x7a,
	0x4e, 0x73, 0x36, 0xa2, 0x0f, 0xb9, 0xcc, 0x8f, 0x60, 0xf7, 0x53, 0x8d, 0x85, 0x54, 0x99, 0x92,
	0xea, 0xee, 0xbf, 0x42, 0x9e, 0xc2, 0x9e, 0x49, 0xbc, 0x48, 0xcb, 0xca, 0x24, 0x1f, 0x00, 0x90,
	0x3f, 0xb6, 0xbe, 0x15, 0x51, 0x87, 0x2d, 0x69, 0xa9, 0x5c, 0x1a, 0xb4, 0x01, 0x6a, 0x17, 0x93,
	0xb4, 0x40, 0xba, 0x02, 0xda, 0x76, 0x5f, 0x74, 0x01, 0x7e, 0x06, 0x8f, 0x49, 0x6a, 0x8e, 0xb2,
	0xd4, 0x3a, 0x27, 0x59, 0x72, 0xa2, 0x16, 0xe0, 0xfe, 0xf5, 0x32, 0xab, 0xe2, 0x76, 0xab, 0xc2,
	0xdf, 0xc1, 0x53, 0x73, 0x08, 0x6d, 0xf1, 0x3f, 0x1f, 0x34, 0x27, 0x1b, 0x05, 0x2e, 0xf3, 0xa2,
	0x4b, 0x70, 0xac, 0xa5, 0xdc, 0x07, 0x3f, 0xcd, 0x12, 0xbc, 0xd5, 0xcf, 0x41, 0x03, 0x3a, 0x01,
	0xcf, 0x76, 0xf1, 0x0d, 0x6c, 0x0b, 0xdc, 0xac, 0x8d, 0x8b, 0x6c, 0x0c, 0x7d, 0x22, 0xca, 0xd0,
	0x89, 0x3c, 0x6b, 0x5b, 0xda, 0x67, 0x48, 0x68, 0x9e, 0x4f, 0x60, 0x68, 0x2a, 0xd9, 0x4b, 0xbb,
	0xf9, 0xfb, 0x8a, 0xb4, 0xda, 0x44, 0xab, 0xcd, 0x51, 0x92, 0x1a, 0x87, 0xde, 0x0a, 0xa5, 0xd1,
	0xda, 0xd1, 0x65, 0xfa, 0xd7, 0x15, 0xc4, 0xf1, 0xd7, 0x5a, 0x47, 0x2d, 0x4d, 0x04, 0xde, 0x0a,
	0xa5, 0x56, 0xf9, 0x33, 0x5d, 0x51, 0xfc, 0x05, 0xfc, 0x67, 0xb2, 0x9b, 0xb7, 0xa2, 0xbd, 0x6f,
	0xed, 0x2b, 0x01, 0x7e, 0x01, 0x20, 0x70, 0x89, 0xe9, 0xa6, 0x52, 0xed, 0x3f, 0x60, 0x62, 0x33,
	0x92, 0x6b, 0xdf, 0x47, 0x6b, 0xad, 0x67, 0x59, 0xbb, 0xe8, 0xd3, 0xab, 0x3d, 0xfd, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0x74, 0xb6, 0x2a, 0xc2, 0x05, 0x00, 0x00,
}
