name: ci_rgbx
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci_rgbx:
    name: ci_rgbx
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
        id: go
      - name: deploy
        run: |
          make docker-compose dapp=rgbx
      - name: cleanup
        if: always()
        run: |
          make docker-compose-down dapp=rgbx
