name: ci_evm
on: [push,pull_request]

jobs:
  ci_evm:
    name: ci_evm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: deploy
        run: |
          make docker-compose dapp=evm
          make docker-compose-down dapp=evm