name: ci_relay
on: [push,pull_request]

jobs:
  ci_relay:
    name: ci_relay
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: set go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: |
          make docker-compose dapp=relay
          make docker-compose-down dapp=relay
