name: ci_paracross_bls
on: [push,pull_request]

jobs:
  ci_paracross:
    name: ci_paracross_bls
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: set go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: |
          make docker-compose dapp=paracross extra=1
          make docker-compose-down dapp=paracross
