name: ci_parachain_rollup
on: [push,pull_request]

jobs:
  paracross:
    name: ci_parachain_rollup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: deploy
        run: |
          make docker-compose dapp=rollup
          make docker-compose-down dapp=rollup
