// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncTxConfig struct {
	Chain33Host          string   `protobuf:"bytes,1,opt,name=chain33host,proto3" json:"chain33host,omitempty"`
	PushHost             string   `protobuf:"bytes,2,opt,name=pushHost,proto3" json:"pushHost,omitempty"`
	PushName             string   `protobuf:"bytes,3,opt,name=pushName,proto3" json:"pushName,omitempty"`
	PushBind             string   `protobuf:"bytes,4,opt,name=pushBind,proto3" json:"pushBind,omitempty"`
	MaturityDegree       int32    `protobuf:"varint,5,opt,name=maturityDegree,proto3" json:"maturityDegree,omitempty"`
	FetchHeightPeriodMs  int64    `protobuf:"varint,9,opt,name=fetchHeightPeriodMs,proto3" json:"fetchHeightPeriodMs,omitempty"`
	StartSyncHeight      int64    `protobuf:"varint,10,opt,name=startSyncHeight,proto3" json:"startSyncHeight,omitempty"`
	StartSyncSequence    int64    `protobuf:"varint,11,opt,name=startSyncSequence,proto3" json:"startSyncSequence,omitempty"`
	StartSyncHash        string   `protobuf:"bytes,12,opt,name=startSyncHash,proto3" json:"startSyncHash,omitempty"`
	KeepAliveDuration    int64    `protobuf:"varint,13,opt,name=keepAliveDuration,proto3" json:"keepAliveDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTxConfig) Reset()         { *m = SyncTxConfig{} }
func (m *SyncTxConfig) String() string { return proto.CompactTextString(m) }
func (*SyncTxConfig) ProtoMessage()    {}
func (*SyncTxConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *SyncTxConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTxConfig.Unmarshal(m, b)
}
func (m *SyncTxConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTxConfig.Marshal(b, m, deterministic)
}
func (m *SyncTxConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTxConfig.Merge(m, src)
}
func (m *SyncTxConfig) XXX_Size() int {
	return xxx_messageInfo_SyncTxConfig.Size(m)
}
func (m *SyncTxConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTxConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTxConfig proto.InternalMessageInfo

func (m *SyncTxConfig) GetChain33Host() string {
	if m != nil {
		return m.Chain33Host
	}
	return ""
}

func (m *SyncTxConfig) GetPushHost() string {
	if m != nil {
		return m.PushHost
	}
	return ""
}

func (m *SyncTxConfig) GetPushName() string {
	if m != nil {
		return m.PushName
	}
	return ""
}

func (m *SyncTxConfig) GetPushBind() string {
	if m != nil {
		return m.PushBind
	}
	return ""
}

func (m *SyncTxConfig) GetMaturityDegree() int32 {
	if m != nil {
		return m.MaturityDegree
	}
	return 0
}

func (m *SyncTxConfig) GetFetchHeightPeriodMs() int64 {
	if m != nil {
		return m.FetchHeightPeriodMs
	}
	return 0
}

func (m *SyncTxConfig) GetStartSyncHeight() int64 {
	if m != nil {
		return m.StartSyncHeight
	}
	return 0
}

func (m *SyncTxConfig) GetStartSyncSequence() int64 {
	if m != nil {
		return m.StartSyncSequence
	}
	return 0
}

func (m *SyncTxConfig) GetStartSyncHash() string {
	if m != nil {
		return m.StartSyncHash
	}
	return ""
}

func (m *SyncTxConfig) GetKeepAliveDuration() int64 {
	if m != nil {
		return m.KeepAliveDuration
	}
	return 0
}

type Log struct {
	Loglevel             string   `protobuf:"bytes,1,opt,name=loglevel,proto3" json:"loglevel,omitempty"`
	LogConsoleLevel      string   `protobuf:"bytes,2,opt,name=logConsoleLevel,proto3" json:"logConsoleLevel,omitempty"`
	LogFile              string   `protobuf:"bytes,3,opt,name=logFile,proto3" json:"logFile,omitempty"`
	MaxFileSize          uint32   `protobuf:"varint,4,opt,name=maxFileSize,proto3" json:"maxFileSize,omitempty"`
	MaxBackups           uint32   `protobuf:"varint,5,opt,name=maxBackups,proto3" json:"maxBackups,omitempty"`
	MaxAge               uint32   `protobuf:"varint,6,opt,name=maxAge,proto3" json:"maxAge,omitempty"`
	LocalTime            bool     `protobuf:"varint,7,opt,name=localTime,proto3" json:"localTime,omitempty"`
	Compress             bool     `protobuf:"varint,8,opt,name=compress,proto3" json:"compress,omitempty"`
	CallerFile           bool     `protobuf:"varint,9,opt,name=callerFile,proto3" json:"callerFile,omitempty"`
	CallerFunction       bool     `protobuf:"varint,10,opt,name=callerFunction,proto3" json:"callerFunction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLoglevel() string {
	if m != nil {
		return m.Loglevel
	}
	return ""
}

func (m *Log) GetLogConsoleLevel() string {
	if m != nil {
		return m.LogConsoleLevel
	}
	return ""
}

func (m *Log) GetLogFile() string {
	if m != nil {
		return m.LogFile
	}
	return ""
}

func (m *Log) GetMaxFileSize() uint32 {
	if m != nil {
		return m.MaxFileSize
	}
	return 0
}

func (m *Log) GetMaxBackups() uint32 {
	if m != nil {
		return m.MaxBackups
	}
	return 0
}

func (m *Log) GetMaxAge() uint32 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *Log) GetLocalTime() bool {
	if m != nil {
		return m.LocalTime
	}
	return false
}

func (m *Log) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *Log) GetCallerFile() bool {
	if m != nil {
		return m.CallerFile
	}
	return false
}

func (m *Log) GetCallerFunction() bool {
	if m != nil {
		return m.CallerFunction
	}
	return false
}

type EthRelayerCfg struct {
	EthChainName         string   `protobuf:"bytes,1,opt,name=ethChainName,proto3" json:"ethChainName,omitempty"`
	EthProvider          []string `protobuf:"bytes,2,rep,name=ethProvider,proto3" json:"ethProvider,omitempty"`
	EthProviderCli       []string `protobuf:"bytes,3,rep,name=ethProviderCli,proto3" json:"ethProviderCli,omitempty"`
	BridgeRegistry       string   `protobuf:"bytes,4,opt,name=bridgeRegistry,proto3" json:"bridgeRegistry,omitempty"`
	EthMaturityDegree    int32    `protobuf:"varint,5,opt,name=ethMaturityDegree,proto3" json:"ethMaturityDegree,omitempty"`
	EthBlockFetchPeriod  int32    `protobuf:"varint,6,opt,name=ethBlockFetchPeriod,proto3" json:"ethBlockFetchPeriod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EthRelayerCfg) Reset()         { *m = EthRelayerCfg{} }
func (m *EthRelayerCfg) String() string { return proto.CompactTextString(m) }
func (*EthRelayerCfg) ProtoMessage()    {}
func (*EthRelayerCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *EthRelayerCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthRelayerCfg.Unmarshal(m, b)
}
func (m *EthRelayerCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthRelayerCfg.Marshal(b, m, deterministic)
}
func (m *EthRelayerCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthRelayerCfg.Merge(m, src)
}
func (m *EthRelayerCfg) XXX_Size() int {
	return xxx_messageInfo_EthRelayerCfg.Size(m)
}
func (m *EthRelayerCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_EthRelayerCfg.DiscardUnknown(m)
}

var xxx_messageInfo_EthRelayerCfg proto.InternalMessageInfo

func (m *EthRelayerCfg) GetEthChainName() string {
	if m != nil {
		return m.EthChainName
	}
	return ""
}

func (m *EthRelayerCfg) GetEthProvider() []string {
	if m != nil {
		return m.EthProvider
	}
	return nil
}

func (m *EthRelayerCfg) GetEthProviderCli() []string {
	if m != nil {
		return m.EthProviderCli
	}
	return nil
}

func (m *EthRelayerCfg) GetBridgeRegistry() string {
	if m != nil {
		return m.BridgeRegistry
	}
	return ""
}

func (m *EthRelayerCfg) GetEthMaturityDegree() int32 {
	if m != nil {
		return m.EthMaturityDegree
	}
	return 0
}

func (m *EthRelayerCfg) GetEthBlockFetchPeriod() int32 {
	if m != nil {
		return m.EthBlockFetchPeriod
	}
	return 0
}

type Chain33RelayerCfg struct {
	SyncTxConfig            *SyncTxConfig `protobuf:"bytes,1,opt,name=syncTxConfig,proto3" json:"syncTxConfig,omitempty"`
	BridgeRegistryOnChain33 string        `protobuf:"bytes,2,opt,name=bridgeRegistryOnChain33,proto3" json:"bridgeRegistryOnChain33,omitempty"`
	ChainName               string        `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	ChainID4Chain33         int32         `protobuf:"varint,4,opt,name=chainID4Chain33,proto3" json:"chainID4Chain33,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *Chain33RelayerCfg) Reset()         { *m = Chain33RelayerCfg{} }
func (m *Chain33RelayerCfg) String() string { return proto.CompactTextString(m) }
func (*Chain33RelayerCfg) ProtoMessage()    {}
func (*Chain33RelayerCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *Chain33RelayerCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain33RelayerCfg.Unmarshal(m, b)
}
func (m *Chain33RelayerCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain33RelayerCfg.Marshal(b, m, deterministic)
}
func (m *Chain33RelayerCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain33RelayerCfg.Merge(m, src)
}
func (m *Chain33RelayerCfg) XXX_Size() int {
	return xxx_messageInfo_Chain33RelayerCfg.Size(m)
}
func (m *Chain33RelayerCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain33RelayerCfg.DiscardUnknown(m)
}

var xxx_messageInfo_Chain33RelayerCfg proto.InternalMessageInfo

func (m *Chain33RelayerCfg) GetSyncTxConfig() *SyncTxConfig {
	if m != nil {
		return m.SyncTxConfig
	}
	return nil
}

func (m *Chain33RelayerCfg) GetBridgeRegistryOnChain33() string {
	if m != nil {
		return m.BridgeRegistryOnChain33
	}
	return ""
}

func (m *Chain33RelayerCfg) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *Chain33RelayerCfg) GetChainID4Chain33() int32 {
	if m != nil {
		return m.ChainID4Chain33
	}
	return 0
}

type RelayerConfig struct {
	Title                string             `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	JrpcBindAddr         string             `protobuf:"bytes,2,opt,name=jrpcBindAddr,proto3" json:"jrpcBindAddr,omitempty"`
	EthRelayerCfg        []*EthRelayerCfg   `protobuf:"bytes,3,rep,name=ethRelayerCfg,proto3" json:"ethRelayerCfg,omitempty"`
	Chain33RelayerCfg    *Chain33RelayerCfg `protobuf:"bytes,4,opt,name=chain33RelayerCfg,proto3" json:"chain33RelayerCfg,omitempty"`
	Log                  *Log               `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Dbdriver             string             `protobuf:"bytes,6,opt,name=dbdriver,proto3" json:"dbdriver,omitempty"`
	DbPath               string             `protobuf:"bytes,7,opt,name=dbPath,proto3" json:"dbPath,omitempty"`
	DbCache              int32              `protobuf:"varint,8,opt,name=dbCache,proto3" json:"dbCache,omitempty"`
	ProcessWithDraw      bool               `protobuf:"varint,9,opt,name=processWithDraw,proto3" json:"processWithDraw,omitempty"`
	RemindUrl            string             `protobuf:"bytes,10,opt,name=remindUrl,proto3" json:"remindUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RelayerConfig) Reset()         { *m = RelayerConfig{} }
func (m *RelayerConfig) String() string { return proto.CompactTextString(m) }
func (*RelayerConfig) ProtoMessage()    {}
func (*RelayerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *RelayerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayerConfig.Unmarshal(m, b)
}
func (m *RelayerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayerConfig.Marshal(b, m, deterministic)
}
func (m *RelayerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerConfig.Merge(m, src)
}
func (m *RelayerConfig) XXX_Size() int {
	return xxx_messageInfo_RelayerConfig.Size(m)
}
func (m *RelayerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerConfig proto.InternalMessageInfo

func (m *RelayerConfig) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RelayerConfig) GetJrpcBindAddr() string {
	if m != nil {
		return m.JrpcBindAddr
	}
	return ""
}

func (m *RelayerConfig) GetEthRelayerCfg() []*EthRelayerCfg {
	if m != nil {
		return m.EthRelayerCfg
	}
	return nil
}

func (m *RelayerConfig) GetChain33RelayerCfg() *Chain33RelayerCfg {
	if m != nil {
		return m.Chain33RelayerCfg
	}
	return nil
}

func (m *RelayerConfig) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *RelayerConfig) GetDbdriver() string {
	if m != nil {
		return m.Dbdriver
	}
	return ""
}

func (m *RelayerConfig) GetDbPath() string {
	if m != nil {
		return m.DbPath
	}
	return ""
}

func (m *RelayerConfig) GetDbCache() int32 {
	if m != nil {
		return m.DbCache
	}
	return 0
}

func (m *RelayerConfig) GetProcessWithDraw() bool {
	if m != nil {
		return m.ProcessWithDraw
	}
	return false
}

func (m *RelayerConfig) GetRemindUrl() string {
	if m != nil {
		return m.RemindUrl
	}
	return ""
}

type SyncTxReceiptConfig struct {
	Chain33Host          string   `protobuf:"bytes,1,opt,name=chain33host,proto3" json:"chain33host,omitempty"`
	PushHost             string   `protobuf:"bytes,2,opt,name=pushHost,proto3" json:"pushHost,omitempty"`
	PushName             string   `protobuf:"bytes,3,opt,name=pushName,proto3" json:"pushName,omitempty"`
	PushBind             string   `protobuf:"bytes,4,opt,name=pushBind,proto3" json:"pushBind,omitempty"`
	StartSyncHeight      int64    `protobuf:"varint,5,opt,name=startSyncHeight,proto3" json:"startSyncHeight,omitempty"`
	StartSyncSequence    int64    `protobuf:"varint,6,opt,name=startSyncSequence,proto3" json:"startSyncSequence,omitempty"`
	StartSyncHash        string   `protobuf:"bytes,7,opt,name=startSyncHash,proto3" json:"startSyncHash,omitempty"`
	Contracts            []string `protobuf:"bytes,8,rep,name=contracts,proto3" json:"contracts,omitempty"`
	KeepAliveDuration    int64    `protobuf:"varint,9,opt,name=keepAliveDuration,proto3" json:"keepAliveDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTxReceiptConfig) Reset()         { *m = SyncTxReceiptConfig{} }
func (m *SyncTxReceiptConfig) String() string { return proto.CompactTextString(m) }
func (*SyncTxReceiptConfig) ProtoMessage()    {}
func (*SyncTxReceiptConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *SyncTxReceiptConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTxReceiptConfig.Unmarshal(m, b)
}
func (m *SyncTxReceiptConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTxReceiptConfig.Marshal(b, m, deterministic)
}
func (m *SyncTxReceiptConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTxReceiptConfig.Merge(m, src)
}
func (m *SyncTxReceiptConfig) XXX_Size() int {
	return xxx_messageInfo_SyncTxReceiptConfig.Size(m)
}
func (m *SyncTxReceiptConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTxReceiptConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTxReceiptConfig proto.InternalMessageInfo

func (m *SyncTxReceiptConfig) GetChain33Host() string {
	if m != nil {
		return m.Chain33Host
	}
	return ""
}

func (m *SyncTxReceiptConfig) GetPushHost() string {
	if m != nil {
		return m.PushHost
	}
	return ""
}

func (m *SyncTxReceiptConfig) GetPushName() string {
	if m != nil {
		return m.PushName
	}
	return ""
}

func (m *SyncTxReceiptConfig) GetPushBind() string {
	if m != nil {
		return m.PushBind
	}
	return ""
}

func (m *SyncTxReceiptConfig) GetStartSyncHeight() int64 {
	if m != nil {
		return m.StartSyncHeight
	}
	return 0
}

func (m *SyncTxReceiptConfig) GetStartSyncSequence() int64 {
	if m != nil {
		return m.StartSyncSequence
	}
	return 0
}

func (m *SyncTxReceiptConfig) GetStartSyncHash() string {
	if m != nil {
		return m.StartSyncHash
	}
	return ""
}

func (m *SyncTxReceiptConfig) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *SyncTxReceiptConfig) GetKeepAliveDuration() int64 {
	if m != nil {
		return m.KeepAliveDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncTxConfig)(nil), "types.SyncTxConfig")
	proto.RegisterType((*Log)(nil), "types.Log")
	proto.RegisterType((*EthRelayerCfg)(nil), "types.EthRelayerCfg")
	proto.RegisterType((*Chain33RelayerCfg)(nil), "types.Chain33RelayerCfg")
	proto.RegisterType((*RelayerConfig)(nil), "types.RelayerConfig")
	proto.RegisterType((*SyncTxReceiptConfig)(nil), "types.SyncTxReceiptConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x41, 0x6f, 0xeb, 0x44,
	0x10, 0x56, 0xe2, 0x97, 0xb6, 0xde, 0x24, 0xa0, 0x6e, 0x9f, 0x60, 0x85, 0x9e, 0x50, 0x14, 0x21,
	0x94, 0x03, 0x0a, 0xa8, 0x45, 0x02, 0x71, 0x6b, 0x13, 0xaa, 0x87, 0xd4, 0x07, 0xd5, 0xf6, 0x21,
	0x24, 0x6e, 0x9b, 0xf5, 0xd4, 0x5e, 0xba, 0xf6, 0x9a, 0xf5, 0x26, 0x24, 0xdc, 0x38, 0x70, 0xe1,
	0x5f, 0xf1, 0x07, 0xb8, 0xf1, 0x7f, 0xd0, 0xac, 0xed, 0xc4, 0x71, 0x52, 0x09, 0x4e, 0xdc, 0xf2,
	0x7d, 0xdf, 0xec, 0x66, 0x67, 0xe6, 0x9b, 0x31, 0x19, 0x48, 0x93, 0x3d, 0xaa, 0x78, 0x9a, 0x5b,
	0xe3, 0x0c, 0xed, 0xb9, 0x4d, 0x0e, 0xc5, 0xf8, 0x8f, 0x80, 0x0c, 0x1e, 0x36, 0x99, 0x7c, 0xbb,
	0x9e, 0x79, 0x95, 0x8e, 0x48, 0x5f, 0x26, 0x42, 0x65, 0x57, 0x57, 0x89, 0x29, 0x1c, 0xeb, 0x8c,
	0x3a, 0x93, 0x90, 0x37, 0x29, 0xfa, 0x01, 0x39, 0xcb, 0x97, 0x45, 0xf2, 0x1a, 0xe5, 0xae, 0x97,
	0xb7, 0xb8, 0xd6, 0xbe, 0x15, 0x29, 0xb0, 0x60, 0xa7, 0x21, 0xae, 0xb5, 0x1b, 0x95, 0x45, 0xec,
	0xc5, 0x4e, 0x43, 0x4c, 0x3f, 0x26, 0xef, 0xa4, 0xc2, 0x2d, 0xad, 0x72, 0x9b, 0x39, 0xc4, 0x16,
	0x80, 0xf5, 0x46, 0x9d, 0x49, 0x8f, 0xb7, 0x58, 0xfa, 0x19, 0xb9, 0x78, 0x04, 0x27, 0x93, 0xd7,
	0xa0, 0xe2, 0xc4, 0xdd, 0x83, 0x55, 0x26, 0x7a, 0x53, 0xb0, 0x70, 0xd4, 0x99, 0x04, 0xfc, 0x98,
	0x44, 0x27, 0xe4, 0xdd, 0xc2, 0x09, 0xeb, 0x30, 0xc9, 0x52, 0x62, 0xc4, 0x47, 0xb7, 0x69, 0xfa,
	0x09, 0x39, 0xdf, 0x52, 0x0f, 0xf0, 0xf3, 0x12, 0x32, 0x09, 0xac, 0xef, 0x63, 0x0f, 0x05, 0xfa,
	0x11, 0x19, 0xee, 0x2e, 0x10, 0x45, 0xc2, 0x06, 0x3e, 0xa5, 0x7d, 0x12, 0xef, 0x7c, 0x02, 0xc8,
	0xaf, 0xb5, 0x5a, 0xc1, 0x7c, 0x69, 0x85, 0x53, 0x26, 0x63, 0xc3, 0xf2, 0xce, 0x03, 0x61, 0xfc,
	0x67, 0x97, 0x04, 0x77, 0x26, 0xc6, 0x4a, 0x69, 0x13, 0x6b, 0x58, 0x81, 0xae, 0x1a, 0xb0, 0xc5,
	0x98, 0x8f, 0x36, 0xf1, 0xcc, 0x64, 0x85, 0xd1, 0x70, 0xe7, 0x43, 0xca, 0x26, 0xb4, 0x69, 0xca,
	0xc8, 0xa9, 0x36, 0xf1, 0xad, 0xd2, 0x75, 0x2b, 0x6a, 0x88, 0x3d, 0x4e, 0xc5, 0x1a, 0x7f, 0x3e,
	0xa8, 0x5f, 0xc1, 0x37, 0x63, 0xc8, 0x9b, 0x14, 0xfd, 0x90, 0x90, 0x54, 0xac, 0x6f, 0x84, 0x7c,
	0x5a, 0xe6, 0x85, 0xef, 0xc5, 0x90, 0x37, 0x18, 0xfa, 0x1e, 0x39, 0x49, 0xc5, 0xfa, 0x3a, 0x06,
	0x76, 0xe2, 0xb5, 0x0a, 0xd1, 0x57, 0x24, 0xd4, 0x46, 0x0a, 0xfd, 0x56, 0xa5, 0xc0, 0x4e, 0x47,
	0x9d, 0xc9, 0x19, 0xdf, 0x11, 0x98, 0x97, 0x34, 0x69, 0x6e, 0xa1, 0x28, 0xd8, 0x99, 0x17, 0xb7,
	0x18, 0xff, 0x51, 0x0a, 0xad, 0xc1, 0xfa, 0x07, 0x87, 0x5e, 0x6d, 0x30, 0xe8, 0x90, 0x0a, 0x2d,
	0x33, 0xe9, 0xcb, 0x48, 0x7c, 0x4c, 0x8b, 0x1d, 0xff, 0xde, 0x25, 0xc3, 0xaf, 0x5d, 0xc2, 0x41,
	0x8b, 0x0d, 0xd8, 0xd9, 0x63, 0x4c, 0xc7, 0x64, 0x00, 0x2e, 0x99, 0xa1, 0x83, 0xbd, 0x2f, 0xcb,
	0x8a, 0xee, 0x71, 0x58, 0x11, 0x70, 0xc9, 0xbd, 0x35, 0x2b, 0x15, 0x81, 0x65, 0xdd, 0x51, 0x80,
	0xae, 0x6f, 0x50, 0xf8, 0xff, 0x0d, 0x38, 0xd3, 0x8a, 0x05, 0x3e, 0xa8, 0xc5, 0x62, 0xdc, 0xc2,
	0xaa, 0x28, 0x06, 0x0e, 0xb1, 0x2a, 0x9c, 0xdd, 0x54, 0x5e, 0x6f, 0xb1, 0xe8, 0x0c, 0x70, 0xc9,
	0x9b, 0x63, 0xa6, 0x3f, 0x14, 0xd0, 0xf7, 0xe0, 0x92, 0x1b, 0x6d, 0xe4, 0xd3, 0x2d, 0x9a, 0xbc,
	0xb4, 0xb7, 0x2f, 0x7e, 0x8f, 0x1f, 0x93, 0xc6, 0x7f, 0x75, 0xc8, 0xf9, 0xac, 0x9c, 0xda, 0x46,
	0x2d, 0xbe, 0x20, 0x83, 0xa2, 0x31, 0xed, 0xbe, 0x16, 0xfd, 0xcb, 0x8b, 0xa9, 0x5f, 0x06, 0xd3,
	0xe6, 0x22, 0xe0, 0x7b, 0x81, 0xf4, 0x4b, 0xf2, 0xfe, 0x7e, 0x02, 0xdf, 0x65, 0xd5, 0xed, 0x95,
	0xfd, 0x9e, 0x93, 0xd1, 0x12, 0x72, 0x5b, 0xfb, 0xd2, 0x88, 0x3b, 0x02, 0xed, 0xec, 0xc1, 0x37,
	0xf3, 0xcf, 0xeb, 0xfb, 0x5e, 0xf8, 0xa4, 0xda, 0xf4, 0xf8, 0xb7, 0x80, 0x0c, 0xeb, 0x4c, 0xca,
	0x37, 0xbd, 0x24, 0x3d, 0xa7, 0x9c, 0xae, 0x3b, 0x5a, 0x02, 0x6c, 0xf7, 0x4f, 0x36, 0x97, 0xb8,
	0x56, 0xae, 0xa3, 0xc8, 0x56, 0xcf, 0xdb, 0xe3, 0xe8, 0x57, 0x64, 0x08, 0x4d, 0x8f, 0xf8, 0x5e,
	0xf6, 0x2f, 0x5f, 0x56, 0x75, 0xd8, 0xf3, 0x0f, 0xdf, 0x0f, 0xa5, 0xb7, 0xe4, 0x5c, 0xb6, 0xeb,
	0xea, 0xdf, 0xdc, 0xbf, 0x64, 0xd5, 0xf9, 0x83, 0xba, 0xf3, 0xc3, 0x23, 0xf4, 0x15, 0x09, 0xb4,
	0x89, 0x7d, 0xcb, 0xfb, 0x97, 0xa4, 0x3a, 0x79, 0x67, 0x62, 0x8e, 0x34, 0x8e, 0x4a, 0xb4, 0x88,
	0xac, 0x5a, 0x81, 0xf5, 0x5d, 0x0e, 0xf9, 0x16, 0xe3, 0xf0, 0x45, 0x8b, 0x7b, 0xe1, 0x12, 0x3f,
	0x61, 0x21, 0xaf, 0x10, 0x0e, 0x7c, 0xb4, 0x98, 0x09, 0x99, 0x80, 0x9f, 0xae, 0x1e, 0xaf, 0x21,
	0x56, 0x39, 0xb7, 0x46, 0x42, 0x51, 0xfc, 0xa0, 0x5c, 0x32, 0xb7, 0xe2, 0x97, 0x6a, 0xc2, 0xda,
	0x34, 0x76, 0xcb, 0x42, 0xaa, 0xb2, 0xe8, 0x7b, 0xab, 0xfd, 0x84, 0x85, 0x7c, 0x47, 0x8c, 0xff,
	0xee, 0x92, 0x8b, 0xd2, 0x24, 0x1c, 0x24, 0xa8, 0xdc, 0xfd, 0xaf, 0x1f, 0x8d, 0x23, 0xab, 0xbd,
	0xf7, 0x1f, 0x56, 0xfb, 0xc9, 0xbf, 0x5e, 0xed, 0xa7, 0xc7, 0x56, 0x3b, 0xfa, 0xda, 0x64, 0xce,
	0x0a, 0xe9, 0x70, 0x9b, 0x05, 0xde, 0xd7, 0x35, 0x71, 0x7c, 0xf1, 0x87, 0xcf, 0x2c, 0xfe, 0x1b,
	0xf2, 0xe3, 0xd9, 0x74, 0xfa, 0xa9, 0xb7, 0xc0, 0xe2, 0xc4, 0x7f, 0x9f, 0xaf, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x9c, 0x3e, 0x6e, 0xaf, 0x07, 0x00, 0x00,
}
